project:
  type: book

book:
  title: "R 医学统计学"
  author: "Frank Gao"
  date: "8/18/2024"
  date-format: "YYYY[年]M[月]D[日]"
  
  reader-mode: true
  cover-image: cover.png
  favicon: favicon.png
  
  site-url: https://qbgaoo.github.io/r4ms
  repo-url: https://github.com/qbgaoo/r4ms
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - quarto.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [flatly, flatly.scss]
      dark:  [darkly, darkly.scss]
    code-copy: hover
    code-annotations: hover
    smooth-scroll: true

editor: visual

