project:
  type: book

book:
  title: "R for Medical Statistics"
  reader-mode: true
  cover-image: cover.png
  favicon: favicon.png
  
  site-url: https://qbgaoo.github.io/r4ms
  repo-url: https://qbgaoo.github.io/r4ms
  repo-actions: [edit, issue]
   
  chapters:
    - index.qmd
    - preface.qmd
    - introduction.qmd
    
    - part: basic-stat.qmd
      chapters:
        - quat-data-statdesc.qmd
        - normal-distribution.qmd
        - statistical-inference.qmd
        - hypothesis-test.qmd
        - ttest.qmd
        - anova.qmd
        - count-data-statdesc.qmd
        - discrete-data-dist.qmd
        - chi-square-test.qmd
        - nonparametric-test.qmd
        - regression-correlation.qmd
        
    - part: advanced-stat.qmd
      chapters:
        - multifactor-anova.qmd
        - repeated-measurement.qmd
        - general-linear-model.qmd
        - multivariate-groups-diff.qmd
        - multiple-linear-regression.qmd
        - logistic-regression.qmd
        - generalized-linear-model.qmd
        - survival-analysis.qmd
        - cluster-analysis.qmd
        - discriminant-analysis.qmd
        - pca-factor-analysis.qmd
        - canonical-correlation.qmd
        - structural-equation.qmd
        - multilevel-model.qmd
        - comprehensive-evaluation.qmd
        - community-interfere.qmd
        - scale-develop.qmd
        - meta-analysis.qmd
        - general-estimat-equation.qmd
        
    - part: stat-anal-report.qmd
      chapters: 
        - quarto.qmd
        - pilot-project.qmd
        - memo.qmd

format:
  html:
    html-math-method: katex
    
    theme:
      light: [flatly, flatly.scss]
      dark:  [darkly, darkly.scss]
    code-copy: hover
    code-annotations: hover
    smooth-scroll: true
    
editor: visual

filters:
  - example-numbering.lua

