project:
  type: book

book:
  title: "R 医学统计学"
  reader-mode: true
  cover-image: cover.png
  favicon: favicon.png
  
  site-url: https://qbgaoo.github.io/r4ms
  repo-url: https://github.com/qbgaoo/r4ms
  repo-actions: [edit, issue]
  
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: basic-stat.qmd
      chapters:
        - quat-data-stat-desc.qmd
        - ttest.qmd
        
    - part: stat-anal-report.qmd
      chapters: 
        - quarto.qmd

format:
  html:
    theme:
      light: [flatly, flatly.scss]
      dark:  [darkly, darkly.scss]
    code-copy: hover
    code-annotations: hover
    smooth-scroll: true

editor: visual

