project:
  type: book

book:
  title: "R for Medical Statistics"
  reader-mode: true
  cover-image: cover.png
  favicon: favicon.png
  
  site-url: https://qbgaoo.github.io/r4ms
  repo-url: https://qbgaoo.github.io/r4ms
  repo-actions: [edit, issue]
   
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    
    - part: basic-stat.qmd
      chapters:
        - quat-data-stat-desc.qmd
        - normal-distribution.qmd
        - statistical-inference.qmd
        - hypothesis-test.qmd
        - ttest.qmd
        - anova.qmd
        - count-data-stat-desc.qmd
        - discrete-data-dist.qmd
        - chi-square-test.qmd
        - nonparametric-test.qmd
        - reg-and-corr.qmd
        
    - part: advanced-stat.qmd
      chapters:
        - multi-factor-anova.qmd
        - repeated-measure.qmd
        - general-linear-model.qmd
        - logistic-regression.qmd
        - cox-regression.qmd
        - ordered-cat-data.qmd
        
    - part: stat-anal-report.qmd
      chapters: 
        - quarto.qmd
        - pilot-project.qmd
        - memo.qmd

format:
  html:
    html-math-method: katex
    
    theme:
      light: [flatly, flatly.scss]
      dark:  [darkly, darkly.scss]
    code-copy: hover
    code-annotations: hover
    smooth-scroll: true

editor: visual

filters:
  - example-numbering.lua

