<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>18&nbsp; Multiple linear regression analysis – R for Medical Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./logistic-regression.html" rel="next">
<link href="./multivariate-groups-diff.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./advanced-stat.html">Advanced methods</a></li><li class="breadcrumb-item"><a href="./multiple-linear-regression.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple linear regression analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R for Medical Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://qbgaoo.github.io/r4ms" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-git"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./basic-stat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quat-data-statdesc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statistical description of quantitative data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Normal distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Statistical inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-data-statdesc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistical description of count data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discrete-data-dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Distributions of discrete variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chi-square-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chi-square test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonparametric-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Nonparametric Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Bivariate regression and correlation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./advanced-stat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Advanced methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multifactor-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Multifactor ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repeated-measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Repeated measures ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general-linear-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">General linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multivariate-groups-diff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multivariate data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-linear-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple linear regression analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic regression analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./generalized-linear-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Generalized linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Survival analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Cox regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./generalized-estimating-equation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Ordered categorical data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stat-anal-report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Communication</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pilot-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">A case to analyze</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./memo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Memo for future programming</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#prerequisite" id="toc-prerequisite" class="nav-link active" data-scroll-target="#prerequisite"><span class="header-section-number">18.1</span> Prerequisite</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression"><span class="header-section-number">18.2</span> Multiple linear regression</a>
  <ul class="collapse">
  <li><a href="#multiple-linear-regression-model" id="toc-multiple-linear-regression-model" class="nav-link" data-scroll-target="#multiple-linear-regression-model"><span class="header-section-number">18.2.1</span> Multiple linear regression model</a></li>
  <li><a href="#estimating-regression-coefficients" id="toc-estimating-regression-coefficients" class="nav-link" data-scroll-target="#estimating-regression-coefficients"><span class="header-section-number">18.2.2</span> Estimating regression coefficients</a></li>
  <li><a href="#evaluating-the-model" id="toc-evaluating-the-model" class="nav-link" data-scroll-target="#evaluating-the-model"><span class="header-section-number">18.2.3</span> Evaluating the model</a></li>
  <li><a href="#standardized-partial-regression" id="toc-standardized-partial-regression" class="nav-link" data-scroll-target="#standardized-partial-regression"><span class="header-section-number">18.2.4</span> Standardized partial regression</a></li>
  </ul></li>
  <li><a href="#independent-variable-selection" id="toc-independent-variable-selection" class="nav-link" data-scroll-target="#independent-variable-selection"><span class="header-section-number">18.3</span> Independent variable selection</a>
  <ul class="collapse">
  <li><a href="#all-subsets-regression" id="toc-all-subsets-regression" class="nav-link" data-scroll-target="#all-subsets-regression"><span class="header-section-number">18.3.1</span> All-subsets regression</a></li>
  <li><a href="#stepwise-regression" id="toc-stepwise-regression" class="nav-link" data-scroll-target="#stepwise-regression"><span class="header-section-number">18.3.2</span> Stepwise regression</a></li>
  </ul></li>
  <li><a href="#application-of-multiple-linear-regression-and-some-considerations" id="toc-application-of-multiple-linear-regression-and-some-considerations" class="nav-link" data-scroll-target="#application-of-multiple-linear-regression-and-some-considerations"><span class="header-section-number">18.4</span> Application of multiple linear regression and some considerations</a>
  <ul class="collapse">
  <li><a href="#application-of-multiple-linear-regression" id="toc-application-of-multiple-linear-regression" class="nav-link" data-scroll-target="#application-of-multiple-linear-regression"><span class="header-section-number">18.4.1</span> Application of multiple linear regression</a></li>
  <li><a href="#considerations-for-multiple-linear-regression" id="toc-considerations-for-multiple-linear-regression" class="nav-link" data-scroll-target="#considerations-for-multiple-linear-regression"><span class="header-section-number">18.4.2</span> Considerations for multiple linear regression</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://qbgaoo.github.io/r4ms/edit/main/multiple-linear-regression.qmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://qbgaoo.github.io/r4ms/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./advanced-stat.html">Advanced methods</a></li><li class="breadcrumb-item"><a href="./multiple-linear-regression.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple linear regression analysis</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple linear regression analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Multiple linear regression is a statistical technique used to model the relationship between one dependent (response) variable and two or more independent (predictor) variables. It extends simple linear regression, which only considers one predictor variable, to situations where multiple variables contribute to predicting the outcome.</p>
<section id="prerequisite" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="prerequisite"><span class="header-section-number">18.1</span> Prerequisite</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lm.beta)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(equatiomatic)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(olsrr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="multiple-linear-regression" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="multiple-linear-regression"><span class="header-section-number">18.2</span> Multiple linear regression</h2>
<section id="multiple-linear-regression-model" class="level3" data-number="18.2.1">
<h3 data-number="18.2.1" class="anchored" data-anchor-id="multiple-linear-regression-model"><span class="header-section-number">18.2.1</span> Multiple linear regression model</h3>
<p>The general form for multiple linear regression model is:</p>
<p><span class="math display">
Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \cdots + \beta_nX_n + \epsilon
</span></p>
<p>where <span class="math inline">Y</span> is the dependent variable, <span class="math inline">X_1, X_2, …, X_n</span> are the independent variables, <span class="math inline">\beta_0</span> is the intercept (the value of <span class="math inline">Y</span> when all <span class="math inline">X</span>’s are zero), <span class="math inline">\beta_1, \beta_2, …, \beta_n</span> are the coefficients for each independent variable, <span class="math inline">\epsilon</span> is the error term.</p>
<p>Multiple minear regression relies on several key assumptions to produce valid results. If these assumptions are violated, the model’s results may be biased or misleading. Here are the primary assumptions:</p>
<ol type="1">
<li>The relationship between the dependent and independent variables must be linear.</li>
<li>Observations should be independent of each other.</li>
<li>The variance of the residuals should be constant across all levels of the independent variables.</li>
<li>The residuals (errors) should be normally distributed.</li>
</ol>
</section>
<section id="estimating-regression-coefficients" class="level3" data-number="18.2.2">
<h3 data-number="18.2.2" class="anchored" data-anchor-id="estimating-regression-coefficients"><span class="header-section-number">18.2.2</span> Estimating regression coefficients</h3>
<p>To estimate the regression coefficients <span class="math inline">\beta_0, \beta_1, \dots, \beta_n</span>, use statistical software to fit the model to your data. This process minimizes the sum of the squared differences between the observed and predicted values (ordinary least squares, or OLS). The OLS estimator for <span class="math inline">\boldsymbol{\beta}</span> is:</p>
<p><span class="math display">
\hat{\boldsymbol{\beta}} = (\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{Y}
</span></p>
<p>This formula minimizes the sum of squared residuals and provides the best linear unbiased estimates of the coefficients under the assumptions of the classical linear regression model.</p>
<div id="ex-18-01" class="example">
<strong>Example 1:</strong> 
<p>Given the measurements of total serum cholesterol (X1), triglycerides (X2), fasting insulin (X3), glycated hemoglobin (X4), and fasting blood glucose (Y) from 27 diabetic patients, establish a multiple linear regression equation for fasting blood glucose with the other indicators.</p>
</div>
<div>
<p><a href="datasets/ex18-01.csv" download="ex18-01.csv" class="btn btn-success"> <i class="bi bi-database-fill-down"></i> Download data </a></p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datasets/ex18-01.csv"</span>, <span class="at">show_col_types =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can use <code>lm()</code> function to perform the regression analysis, with <span class="math inline">Y</span> as the dependent variable and <span class="math inline">X1</span>, <span class="math inline">X2</span>, <span class="math inline">X3</span>, <span class="math inline">X4</span> as the independent variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> df)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)          X1          X2          X3          X4 
#&gt;   5.9432678   0.1424465   0.3514655  -0.2705853   0.6382012</code></pre>
</div>
</div>
<p>The code can also be written as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> ., <span class="at">data =</span> df)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)          X1          X2          X3          X4 
#&gt;   5.9432678   0.1424465   0.3514655  -0.2705853   0.6382012</code></pre>
</div>
</div>
<p>You can use the <code>coef()</code> function to extract regression coefficients from the model. The <code>extract_eq()</code> function from <code>equatiomatic</code> package can extract regression equation from the fitted model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_eq</span>(model, <span class="at">use_coefs =</span> T, <span class="at">coef_digits =</span> <span class="dv">4</span>, <span class="at">font_size =</span> <span class="st">"small"</span>)     </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><span class="math display">
\small
\begin{aligned}
\operatorname{\widehat{Y}} &amp;= 5.9433 + 0.1424(\operatorname{X1}) + 0.3515(\operatorname{X2}) - 0.2706(\operatorname{X3}) + 0.6382(\operatorname{X4})
\end{aligned}
</span></p>
</div>
</div>
</section>
<section id="evaluating-the-model" class="level3" data-number="18.2.3">
<h3 data-number="18.2.3" class="anchored" data-anchor-id="evaluating-the-model"><span class="header-section-number">18.2.3</span> Evaluating the model</h3>
<p>In multiple linear regression, hypothesis tests help evaluate the significance of the model and individual predictors, while assumption tests ensure that the model is reliable. The F-test determines if the model is significant overall, t-tests assess the impact of individual predictors, and R² and adjusted R² indicate the model’s explanatory power. Residual analysis further ensures the validity of the model’s assumptions.</p>
<ol type="1">
<li><strong>F-test</strong></li>
</ol>
<ul>
<li><span class="math inline">H_0</span>: All regression coefficients are zero, meaning none of the independent variables have a significant effect on the dependent variable.</li>
<li><span class="math inline">H_1</span>: At least one regression coefficient is not zero, indicating that at least one independent variable has a significant effect.</li>
</ul>
<p>The F-test evaluates the overall significance of the model. The formula for the F-statistic is:</p>
<p><span class="math display">
F = \frac{MSR}{MSE} = \frac{\text{Mean Square Regression}}{\text{Mean Square Error}}
</span></p>
<p>If the F-value is large and the p-value is small (typically &lt; 0.05), reject the null hypothesis, suggesting the model is statistically significant.</p>
<ol start="2" type="1">
<li><strong>t-test</strong></li>
</ol>
<ul>
<li><span class="math inline">H_0</span>: A particular regression coefficient is zero, indicating that the corresponding independent variable has no significant effect on the dependent variable.</li>
<li><span class="math inline">H_1</span>: The regression coefficient is not zero, implying the independent variable has a significant effect.</li>
</ul>
<p>The t-test for each coefficient is used to assess whether each predictor significantly contributes to the model:</p>
<p><span class="math display">
t = \frac{\hat{\beta}_i}{SE(\hat{\beta}_i)}
</span></p>
<p>where <span class="math inline">\hat{\beta}_i</span> is the estimated coefficient, and <span class="math inline">SE(\hat{\beta}_i)</span> is the standard error.</p>
<p>If the t-value is large and the p-value is small (typically &lt; 0.05), reject the null hypothesis, indicating that the variable has a significant effect on the dependent variable.</p>
<ol start="3" type="1">
<li><strong>Goodness of fit</strong></li>
</ol>
<ul>
<li><p><span class="math inline">R^2</span> (Coefficient of determination)</p>
<p>This indicates the proportion of variance in the dependent variable explained by the independent variables. It ranges from 0 to 1, with higher values suggesting a better fit. The <span class="math inline">R^2</span> is defined as:</p>
<p><span class="math display">
R^2 = 1 - \frac{SS_{\text{residuals}}}{SS_{\text{total}}}
</span></p>
<p>where <span class="math inline">SS_{\text{residuals}}</span> denotes the sum of squared residuals (errors), i.e., the unexplained variance, <span class="math inline">SS_{\text{total}}</span> is the total sum of squares, i.e., the total variance of the dependent variable.</p></li>
<li><p>Adjusted <span class="math inline">R^2</span></p>
<p>It is formulated as:</p>
<p><span class="math display">
\text{adjusted } R^2 = 1 - \left( \frac{(1 - R^2)(n - 1)}{n - p - 1} \right)
</span></p>
<p>where <span class="math inline">n</span> is the number of observations, <span class="math inline">p</span> is the number of predictors (independent variables). This adjustment penalizes models that include too many predictors that don’t contribute to a better fit. A higher adjusted R² indicates a model with strong explanatory power and parsimony.</p></li>
<li><p><span class="math inline">R</span> (Multiple correlation coefficient)</p>
<p>This measures the strength of the linear relationship between a set of independent variables (predictors) and a dependent variable in a multiple linear regression model. The <span class="math inline">R</span> is calculated as:</p>
<p><span class="math display">
R = \sqrt{R^2}
</span></p>
<p>where <span class="math inline">R^2</span> is the coefficient of determination.</p></li>
</ul>
<p>Here <code>summary()</code> is used to produce result summaries of the results from the model fitting functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = Y ~ ., data = df)
#&gt; 
#&gt; Residuals:
#&gt;     Min      1Q  Median      3Q     Max 
#&gt; -3.6268 -1.2004 -0.2276  1.5389  4.4467 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value Pr(&gt;|t|)  
#&gt; (Intercept)   5.9433     2.8286   2.101   0.0473 *
#&gt; X1            0.1424     0.3657   0.390   0.7006  
#&gt; X2            0.3515     0.2042   1.721   0.0993 .
#&gt; X3           -0.2706     0.1214  -2.229   0.0363 *
#&gt; X4            0.6382     0.2433   2.623   0.0155 *
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt; Residual standard error: 2.01 on 22 degrees of freedom
#&gt; Multiple R-squared:  0.6008, Adjusted R-squared:  0.5282 
#&gt; F-statistic: 8.278 on 4 and 22 DF,  p-value: 0.0003121</code></pre>
</div>
</div>
<p>From the result summaries, we can find that the overall model is statistically significant (F-statistic is 8.278, <span class="math inline">p &lt; 0.001</span>), indicating that at least one of the predictors is related to the fasting blood glucose.</p>
<p><span class="math inline">X1</span> (<span class="math inline">t=0.390</span>, <span class="math inline">p=0.7006</span>) and <span class="math inline">X2</span> (<span class="math inline">t=1.721</span>, <span class="math inline">p=0.0993</span>) are not statistically significant predictors, <span class="math inline">X3</span> (<span class="math inline">t=0-2.229</span>, <span class="math inline">p=0.0363</span>) and <span class="math inline">X4</span> (<span class="math inline">t=2.623</span>, <span class="math inline">p=0.0155</span>) are significant in this model.</p>
<p>The <span class="math inline">R^2 = 0.6008</span>, this indicates that approximately 60.08% of the variance in fasting blood glucose is explained by the model, which suggests a moderate fit.</p>
<p>The adjusted <span class="math inline">R^2 = 0.5282</span>, this indicates after adjusting for the number of predictors, the model explains around 52.82% of the variance.</p>
</section>
<section id="standardized-partial-regression" class="level3" data-number="18.2.4">
<h3 data-number="18.2.4" class="anchored" data-anchor-id="standardized-partial-regression"><span class="header-section-number">18.2.4</span> Standardized partial regression</h3>
<p>In multiple linear regression, standardized partial regression coefficients (also known as standardized beta coefficients) are used to compare the relative importance of each predictor variable in the model, as they are measured on the same scale (standard deviations). They are obtained after standardizing both the independent and dependent variables, so that each variable has a mean of zero and a standard deviation of one.</p>
<p>The standardized regression coefficient <span class="math inline">\beta_i^*</span> is computed as:</p>
<p><span class="math display">
\beta_i^* = \beta_i \times \frac{\sigma_{X_i}}{\sigma_Y}
</span></p>
<p>where <span class="math inline">\beta_i</span>is the unstandardized regression coefficient for the predictor<span class="math inline">X_i</span>,<span class="math inline">\sigma_{X_i}</span> is the standard deviation of predictor <span class="math inline">X_i</span>, <span class="math inline">\sigma_Y</span> is the standard deviation of the dependent variable <span class="math inline">Y</span>.</p>
<p>You can obtain standardized coefficients by using the <code>scale()</code> function to standardize the variables before performing the regression. Standardizing ensures that each variable has a mean of 0 and a standard deviation of 1, allowing you to directly interpret the coefficients as standardized coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scale</span>(df) <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> _) <span class="sc">|&gt;</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coefficients</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;   (Intercept)            X1            X2            X3            X4 
#&gt;  6.525869e-16  7.757862e-02  3.093081e-01 -3.394808e-01  3.977418e-01</code></pre>
</div>
</div>
<p>Alternatively, the <code>lm.beta</code> package provides a convenient <code>lm.beta()</code> function that takes an ordinary linear model and returns the standardized coefficients directly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.beta</span>(model) <span class="sc">|&gt;</span> <span class="fu">coef</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)          X1          X2          X3          X4 
#&gt;          NA  0.07757862  0.30930814 -0.33948078  0.39774184</code></pre>
</div>
</div>
<p>In a standardized regression model, the intercept is typically not interpreted because it is not directly comparable to the other variables after standardization. Therefore, it is shown as <code>NA</code> in the output of <code>lm.beta()</code>. Among the predictors, <span class="math inline">X4</span> has the strongest positive effect on <span class="math inline">Y</span>, followed by <span class="math inline">X2</span>. <span class="math inline">X3</span> has a significant negative impact on <span class="math inline">Y</span>, while <span class="math inline">X1</span> has a relatively small effect.</p>
</section>
</section>
<section id="independent-variable-selection" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="independent-variable-selection"><span class="header-section-number">18.3</span> Independent variable selection</h2>
<p>The selection of independent variables refers to the process of choosing the most significant predictors (independent variables) to construct a model in multiple regression analysis or other predictive models. By selecting independent variables, you can improve the model’s prediction performance, simplify the model, and reduce the risk of overfitting. Common methods for independent variable selection include:</p>
<section id="all-subsets-regression" class="level3" data-number="18.3.1">
<h3 data-number="18.3.1" class="anchored" data-anchor-id="all-subsets-regression"><span class="header-section-number">18.3.1</span> All-subsets regression</h3>
<p>All-subsets regression (also called best subset regression) is a method that evaluates all possible subsets of the predictor variables in order to identify the best model or models. This approach is exhaustive, meaning it fits regression models for every possible combination of predictors and selects the one(s) based on specific criteria like adjusted <span class="math inline">R^2</span>, AIC, BIC, or Mallow’s <span class="math inline">C_p</span>.</p>
<ul>
<li><p><strong>Adjusted</strong> <span class="math inline">R^2</span></p>
<p>Adjusted <span class="math inline">R^2</span> is a modified version of the <span class="math inline">R^2</span> that adjusts for the number of predictors (independent variables) in a regression model. Unlike the regular <span class="math inline">R^2</span>, which always increases when new predictors are added, Adjusted <span class="math inline">R^2</span> compensates for the model complexity, ensuring that only significant predictors improve the model’s fit.</p></li>
<li><p><strong>Akaike information criterion (AIC)</strong></p>
<p>AIC is based on information theory and estimates the relative quality of statistical models for a given dataset. It provides a measure of the goodness of fit while penalizing for the number of parameters in the model.</p>
<p>The formula for AIC is:</p>
<p><span class="math display">
AIC = 2k - 2\log(L)
</span></p>
<p>where <span class="math inline">k</span> is the number of parameters in the model, <span class="math inline">L</span> is the likelihood of the model (how well the model fits the data). Among competing models, the one with the lowest AIC is preferred.</p></li>
<li><p><strong>Bayesian information criterion (BIC)</strong></p>
<p>BIC is similar to AIC but includes a stronger penalty for the number of parameters, especially as the sample size increases. BIC is derived from a Bayesian perspective and is more conservative in model selection compared to AIC.</p>
<p>The formula for BIC is:</p>
<p><span class="math display">
BIC = k\log(n) - 2\log(L)
</span></p>
<p>where <span class="math inline">k</span> is the number of parameters in the model, <span class="math inline">n</span> is the sample size, <span class="math inline">L</span> is the likelihood of the model. Like AIC, a lower BIC value indicates a better model.</p></li>
<li><p><strong>Mallow’s</strong> <span class="math inline">C_p</span></p>
<p>Mallows’ <span class="math inline">C_p</span> is a statistical criterion used for model selection in regression analysis. It helps identify models that offer a good balance between complexity (number of predictors) and goodness of fit. Specifically, it is used to compare regression models with different numbers of predictors to select the one that is neither underfitting nor overfitting the data.</p>
<p>Mallows’ <span class="math inline">C_p</span> is defined as:</p>
<p><span class="math display">
C_p = \frac{\text{RSS}_p}{\hat{\sigma}^2} + 2p - n
</span></p>
<p>where <span class="math inline">\text{RSS}_p</span> is the residual sum of squares for the model, <span class="math inline">\hat{\sigma}^2</span> is an estimate of the true error variance, <span class="math inline">p</span> is the number of parameters in the model (including the intercept), <span class="math inline">n</span> is the number of observations.</p>
<ul>
<li>If <span class="math inline">C_p \approx p</span>: The model is considered to have an appropriate number of predictors. The <span class="math inline">C_p</span> value should be close to the number of predictors in the model.</li>
<li>If <span class="math inline">C_p &gt; p</span>: This suggests that the model is overfitting, meaning it’s too complex and is fitting the noise in the data.</li>
<li>If <span class="math inline">C_p &lt; p</span>: This suggests that the model is underfitting, meaning it’s too simple and is missing important predictors.</li>
</ul>
<p>In practice, the goal is to find the model with the lowest <span class="math inline">C_p</span> that is close to <span class="math inline">p</span>.</p></li>
</ul>
<div class="example">
<strong>Example 2:</strong> 
<p>Use the all-subsets regression method to select the independent variables of the data in <a href="#ex-18-01">Example 1</a>.</p>
</div>
<p>The <code>regsubsets()</code> function from <code>leaps</code> package is a tool primarily used for performing best subset selection in regression analysis. It helps identify the best-fitting model with a given number of predictors by comparing all possible subsets of predictors based on specific criteria like Adjusted R-squared, AIC, BIC, <em>etc</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(Y <span class="sc">~</span> ., <span class="at">data =</span> df, <span class="at">nbest =</span> <span class="dv">1</span>, <span class="at">method =</span> <span class="st">"exhaustive"</span>) </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Subset selection object
#&gt; Call: regsubsets.formula(Y ~ ., data = df, nbest = 1, method = "exhaustive")
#&gt; 4 Variables  (and intercept)
#&gt;    Forced in Forced out
#&gt; X1     FALSE      FALSE
#&gt; X2     FALSE      FALSE
#&gt; X3     FALSE      FALSE
#&gt; X4     FALSE      FALSE
#&gt; 1 subsets of each size up to 4
#&gt; Selection Algorithm: exhaustive
#&gt;          X1  X2  X3  X4 
#&gt; 1  ( 1 ) " " " " " " "*"
#&gt; 2  ( 1 ) "*" " " " " "*"
#&gt; 3  ( 1 ) " " "*" "*" "*"
#&gt; 4  ( 1 ) "*" "*" "*" "*"</code></pre>
</div>
</div>
<p>Use the <code>plot()</code> function to visualize different scale values for the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">scale =</span> <span class="st">"adjr2"</span>)   <span class="co"># adjusted R²</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">scale =</span> <span class="st">"Cp"</span>)      <span class="co"># Mallow's Cp</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, <span class="at">scale =</span> <span class="st">"bic"</span>)     <span class="co"># BIC</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multiple-linear-regression_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multiple-linear-regression_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multiple-linear-regression_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Find the best model based on a specific criteria:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(<span class="fu">summary</span>(model)<span class="sc">$</span>adjr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">summary</span>(model)<span class="sc">$</span>cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">summary</span>(model)<span class="sc">$</span>bic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] 3</code></pre>
</div>
</div>
<p>Print the selected variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the model with the largest adjustment R²</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>max_adjr2_index <span class="ot">&lt;-</span> <span class="fu">which.max</span>(<span class="fu">summary</span>(model)<span class="sc">$</span>adjr2)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The model with the maximum adjusted R² is at index:"</span>, max_adjr2_index, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; The model with the maximum adjusted R² is at index: 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gets the variables selected in the model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>selected_vars <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>which[max_adjr2_index, ]</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>selected_vars</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; (Intercept)          X1          X2          X3          X4 
#&gt;        TRUE       FALSE        TRUE        TRUE        TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the selected variables</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>selected_vars_names <span class="ot">&lt;-</span> <span class="fu">names</span>(selected_vars)[selected_vars]</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The selected variables in the best model (with maximum adjusted R²):"</span>, <span class="fu">paste</span>(selected_vars_names, <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; The selected variables in the best model (with maximum adjusted R²): (Intercept), X2, X3, X4</code></pre>
</div>
</div>
<p>Although this method is likely to find the best-fitting model, its computational complexity increases sharply with the increase of the number of independent variables, so it is usually only suitable for the case of a small number of independent variables in practical application.</p>
</section>
<section id="stepwise-regression" class="level3" data-number="18.3.2">
<h3 data-number="18.3.2" class="anchored" data-anchor-id="stepwise-regression"><span class="header-section-number">18.3.2</span> Stepwise regression</h3>
<p>The stepwise regression is a method for selecting the most significant variables in a regression model by adding or removing predictor variables based on specific criteria (e.g., AIC, BIC, p-values). There are three common types of stepwise regression:</p>
<ol type="1">
<li><strong>Forward selection</strong>: Starts with no predictors and adds the most significant predictor at each step.</li>
<li><strong>Backward elimination</strong>: Starts with all predictors and removes the least significant predictor at each step.</li>
<li><strong>Stepwise selection</strong>: A combination of forward selection and backward elimination where predictors can be added or removed at each step based on their significance.</li>
</ol>
<p>The <code>step()</code> function in base R is the most commonly used function for performing stepwise regression based on AIC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a full model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> df)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform stepwise regression using AIC (default)</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>stepwise_model <span class="ot">&lt;-</span> <span class="fu">step</span>(full_model, <span class="at">direction =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Start:  AIC=42.16
#&gt; Y ~ X1 + X2 + X3 + X4
#&gt; 
#&gt;        Df Sum of Sq     RSS    AIC
#&gt; - X1    1    0.6129  89.454 40.343
#&gt; &lt;none&gt;               88.841 42.157
#&gt; - X2    1   11.9627 100.804 43.568
#&gt; - X3    1   20.0635 108.905 45.655
#&gt; - X4    1   27.7939 116.635 47.507
#&gt; 
#&gt; Step:  AIC=40.34
#&gt; Y ~ X2 + X3 + X4
#&gt; 
#&gt;        Df Sum of Sq     RSS    AIC
#&gt; &lt;none&gt;               89.454 40.343
#&gt; + X1    1     0.613  88.841 42.157
#&gt; - X3    1    25.690 115.144 45.159
#&gt; - X2    1    26.530 115.984 45.356
#&gt; - X4    1    32.269 121.723 46.660</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the summary of the final model</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>stepwise_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = Y ~ X2 + X3 + X4, data = df)
#&gt; 
#&gt; Coefficients:
#&gt; (Intercept)           X2           X3           X4  
#&gt;      6.4996       0.4023      -0.2870       0.6632</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_eq</span>(stepwise_model, <span class="at">use_coefs =</span> T, <span class="at">coef_digits =</span> <span class="dv">4</span>, <span class="at">font_size =</span> <span class="st">"small"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><span class="math display">
\small
\begin{aligned}
\operatorname{\widehat{Y}} &amp;= 6.4996 + 0.4023(\operatorname{X2}) - 0.287(\operatorname{X3}) + 0.6632(\operatorname{X4})
\end{aligned}
</span></p>
</div>
</div>
<p>You can use the <code>stepAIC()</code> function from the <code>MASS</code> package, which works similarly to <code>step()</code> but is more flexible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>stepwise_model <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(full_model, <span class="at">direction =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Start:  AIC=42.16
#&gt; Y ~ X1 + X2 + X3 + X4
#&gt; 
#&gt;        Df Sum of Sq     RSS    AIC
#&gt; - X1    1    0.6129  89.454 40.343
#&gt; &lt;none&gt;               88.841 42.157
#&gt; - X2    1   11.9627 100.804 43.568
#&gt; - X3    1   20.0635 108.905 45.655
#&gt; - X4    1   27.7939 116.635 47.507
#&gt; 
#&gt; Step:  AIC=40.34
#&gt; Y ~ X2 + X3 + X4
#&gt; 
#&gt;        Df Sum of Sq     RSS    AIC
#&gt; &lt;none&gt;               89.454 40.343
#&gt; + X1    1     0.613  88.841 42.157
#&gt; - X3    1    25.690 115.144 45.159
#&gt; - X2    1    26.530 115.984 45.356
#&gt; - X4    1    32.269 121.723 46.660</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>stepwise_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = Y ~ X2 + X3 + X4, data = df)
#&gt; 
#&gt; Coefficients:
#&gt; (Intercept)           X2           X3           X4  
#&gt;      6.4996       0.4023      -0.2870       0.6632</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_eq</span>(stepwise_model, <span class="at">use_coefs =</span> T, <span class="at">coef_digits =</span> <span class="dv">4</span>, <span class="at">font_size =</span> <span class="st">"small"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><span class="math display">
\small
\begin{aligned}
\operatorname{\widehat{Y}} &amp;= 6.4996 + 0.4023(\operatorname{X2}) - 0.287(\operatorname{X3}) + 0.6632(\operatorname{X4})
\end{aligned}
</span></p>
</div>
</div>
<p>If you want to use other model selection criteria, the <code>olsrr</code> package provides a more intuitive way to perform stepwise regression, with options to perform forward, backward, and stepwise regression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>stepwise_model <span class="ot">&lt;-</span> <span class="fu">ols_step_both_adj_r2</span>(full_model)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>stepwise_model <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>stepwise_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; 
#&gt;                              Stepwise Summary                             
#&gt; ------------------------------------------------------------------------
#&gt; Step    Variable        AIC        SBC       SBIC       R2       Adj. R2 
#&gt; ------------------------------------------------------------------------
#&gt;  0      Base Model    137.574    140.166    59.411    0.00000    0.00000 
#&gt;  1      X4 (+)        127.028    130.916    49.427    0.37166    0.34653 
#&gt;  2      X1 (+)        123.692    128.876    46.765    0.48434    0.44137 
#&gt;  3      X3 (+)        122.191    128.670    46.208    0.54705    0.48797 
#&gt;  4      X2 (+)        120.780    128.555    46.327    0.60081    0.52823 
#&gt;  5      X1 (-)        118.966    125.445    43.998    0.59805    0.54563 
#&gt; ------------------------------------------------------------------------
#&gt; 
#&gt; Final Model Output 
#&gt; ------------------
#&gt; 
#&gt;                          Model Summary                          
#&gt; ---------------------------------------------------------------
#&gt; R                       0.773       RMSE                 1.820 
#&gt; R-Squared               0.598       MSE                  3.889 
#&gt; Adj. R-Squared          0.546       Coef. Var           16.537 
#&gt; Pred R-Squared          0.365       AIC                118.966 
#&gt; MAE                     1.460       SBC                125.445 
#&gt; ---------------------------------------------------------------
#&gt;  RMSE: Root Mean Square Error 
#&gt;  MSE: Mean Square Error 
#&gt;  MAE: Mean Absolute Error 
#&gt;  AIC: Akaike Information Criteria 
#&gt;  SBC: Schwarz Bayesian Criteria 
#&gt; 
#&gt;                                ANOVA                                
#&gt; -------------------------------------------------------------------
#&gt;                Sum of                                              
#&gt;               Squares        DF    Mean Square      F         Sig. 
#&gt; -------------------------------------------------------------------
#&gt; Regression    133.098         3         44.366    11.407     1e-04 
#&gt; Residual       89.454        23          3.889                     
#&gt; Total         222.552        26                                    
#&gt; -------------------------------------------------------------------
#&gt; 
#&gt;                                   Parameter Estimates                                    
#&gt; ----------------------------------------------------------------------------------------
#&gt;       model      Beta    Std. Error    Std. Beta      t        Sig      lower     upper 
#&gt; ----------------------------------------------------------------------------------------
#&gt; (Intercept)     6.500         2.396                  2.713    0.012     1.543    11.456 
#&gt;          X4     0.663         0.230        0.413     2.880    0.008     0.187     1.140 
#&gt;          X3    -0.287         0.112       -0.360    -2.570    0.017    -0.518    -0.056 
#&gt;          X2     0.402         0.154        0.354     2.612    0.016     0.084     0.721 
#&gt; ----------------------------------------------------------------------------------------</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multiple-linear-regression_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>stepwise_model[[<span class="st">"model"</span>]] <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_eq</span>(<span class="at">use_coefs =</span> T, <span class="at">coef_digits =</span> <span class="dv">4</span>, <span class="at">font_size =</span> <span class="st">"small"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><span class="math display">
\small
\begin{aligned}
\operatorname{\widehat{Y}} &amp;= 6.4996 + 0.6632(\operatorname{X4}) - 0.287(\operatorname{X3}) + 0.4023(\operatorname{X2})
\end{aligned}
</span></p>
</div>
</div>
</section>
</section>
<section id="application-of-multiple-linear-regression-and-some-considerations" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="application-of-multiple-linear-regression-and-some-considerations"><span class="header-section-number">18.4</span> Application of multiple linear regression and some considerations</h2>
<section id="application-of-multiple-linear-regression" class="level3" data-number="18.4.1">
<h3 data-number="18.4.1" class="anchored" data-anchor-id="application-of-multiple-linear-regression"><span class="header-section-number">18.4.1</span> Application of multiple linear regression</h3>
<p>Multiple linear regression is widely used in medical research for predicting patient outcomes, analyzing the effects of various biological markers on health results, and controlling for confounding variables. Below are several scenarios where MLR is applied in the medical field:</p>
<ol type="1">
<li><p><strong>Disease risk prediction</strong></p>
<p>Multiple linear regression can be used to predict disease risk by incorporating multiple biomarkers or clinical variables. For example, factors such as age, weight, cholesterol level, and blood pressure can be used to predict the risk of cardiovascular disease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(heart_disease_risk <span class="sc">~</span> age <span class="sc">+</span> cholesterol <span class="sc">+</span> blood_pressure <span class="sc">+</span> smoking_status, <span class="at">data =</span> patients_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Drug efficacy analysis</strong></p>
<p>In clinical trials, multiple linear regression is useful for evaluating the combined effects of multiple factors on drug efficacy. For example, when assessing blood sugar control in diabetic patients, variables such as drug dosage, age, weight, and lifestyle habits can be included to understand their effects on glucose levels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(fasting_glucose <span class="sc">~</span> drug_dose <span class="sc">+</span> age <span class="sc">+</span> weight <span class="sc">+</span> exercise, <span class="at">data =</span> diabetes_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Controlling for confounding variables</strong></p>
<p>Confounding factors such as age, gender, or lifestyle can affect the relationships between variables. Multiple linear regression helps control for these confounders by incorporating multiple variables, allowing a more accurate estimation of the primary exposure variable’s effect (e.g., treatment method) on health outcomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(treatment_effect <span class="sc">~</span> age <span class="sc">+</span> gender <span class="sc">+</span> treatment_group, <span class="at">data =</span> clinical_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Prognostic model construction</strong></p>
<p>Prognostic models are used to predict survival rates or disease outcomes in medical research. Multiple linear regression helps identify significant factors influencing disease progression and uses these factors to build a prognostic model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(survival_time <span class="sc">~</span> tumor_size <span class="sc">+</span> age <span class="sc">+</span> treatment_type <span class="sc">+</span> physical_activity, <span class="at">data =</span> cancer_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Correlation analysis of physiological indicators</strong></p>
<p>Multiple linear regression can analyze the relationship between different physiological indicators. For example, it can examine how weight, cholesterol, and blood pressure affect a health outcome, such as kidney or heart function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(kidney_function <span class="sc">~</span> weight <span class="sc">+</span> cholesterol <span class="sc">+</span> blood_pressure, <span class="at">data =</span> health_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
</ol>
</section>
<section id="considerations-for-multiple-linear-regression" class="level3" data-number="18.4.2">
<h3 data-number="18.4.2" class="anchored" data-anchor-id="considerations-for-multiple-linear-regression"><span class="header-section-number">18.4.2</span> Considerations for multiple linear regression</h3>
<ol type="1">
<li><p>Multicollinearity: High correlation between independent variables can make the model’s coefficients unstable and inflate standard errors, making it difficult to assess the individual effect of each predictor. Multicollinearity can be assessed using the variance inflation factor (VIF) by <code>vif()</code> function from <code>car</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span><span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> df)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;       X1       X2       X3       X4 
#&gt; 2.185539 1.779862 1.278364 1.266730</code></pre>
</div>
</div></li>
<li><p>Normality and independence of residuals: The model assumes that the residuals are independent and normally distributed. Residual plots and tests like the Shapiro-Wilk test can be used to assess this assumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(model) <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(model) <span class="sc">|&gt;</span> <span class="fu">shapiro.test</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;  Shapiro-Wilk normality test
#&gt; 
#&gt; data:  residuals(model)
#&gt; W = 0.97835, p-value = 0.8233</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multiple-linear-regression_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div></li>
<li><p>Homoscedasticity: The model assumes that the variance of the residuals is constant. If the residual variance is not constant (heteroscedasticity), it can impact the efficiency of the estimates. Residual plots or tests like White’s test can detect heteroscedasticity.</p>
<p>You can use the <code>bptest()</code> function from the <code>lmtest</code> package to conduct a Breusch-Pagan test, a similar test for heteroscedasticity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">bptest</span>(model)  <span class="co"># Breusch-Pagan test for heteroscedasticity</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;  studentized Breusch-Pagan test
#&gt; 
#&gt; data:  model
#&gt; BP = 6.4508, df = 4, p-value = 0.1679</code></pre>
</div>
</div>
<p>As for White’s test specifically, we defined a custom function named <code>whites.test()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>whites.test <span class="ot">&lt;-</span> <span class="cf">function</span>(model) {</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extract the independent variables in the model</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  terms <span class="ot">&lt;-</span> <span class="fu">attr</span>(<span class="fu">terms</span>(model), <span class="st">"term.labels"</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extract the data used in the model</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> model<span class="sc">$</span>model</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create square and interaction terms</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  squared_terms <span class="ot">&lt;-</span> <span class="fu">sapply</span>(terms, <span class="cf">function</span>(term) <span class="fu">paste0</span>(<span class="st">"I("</span>, term, <span class="st">"^2)"</span>))</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  interaction_terms <span class="ot">&lt;-</span> <span class="fu">combn</span>(terms, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">paste</span>(x, <span class="at">collapse =</span> <span class="st">":"</span>))</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Construct the formula of auxiliary regression model</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>  auxiliary_formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">"e2 ~"</span>, </span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">paste</span>(<span class="fu">c</span>(terms, squared_terms, interaction_terms), <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate the square of the residual</span></span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>  e2 <span class="ot">&lt;-</span> <span class="fu">resid</span>(model)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Construct auxiliary regression model</span></span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>  auxiliary_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(auxiliary_formula, <span class="at">data =</span> data)</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># F-test</span></span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>  f_statistic <span class="ot">&lt;-</span> <span class="fu">summary</span>(auxiliary_model)<span class="sc">$</span>fstatistic</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>  p_value <span class="ot">&lt;-</span> <span class="fu">pf</span>(f_statistic[<span class="dv">1</span>], f_statistic[<span class="dv">2</span>], f_statistic[<span class="dv">3</span>], <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">LM_test_statistic =</span> f_statistic[<span class="dv">1</span>],</span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">df1 =</span> f_statistic[<span class="dv">2</span>],</span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">df2 =</span> f_statistic[<span class="dv">3</span>],</span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_value =</span> p_value,</span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">auxiliary_model =</span> auxiliary_model</span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">class</span>(result) <span class="ot">&lt;-</span> <span class="st">"whites.test"</span></span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a>  result</span>
<span id="cb53-37"><a href="#cb53-37" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-38"><a href="#cb53-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-39"><a href="#cb53-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing results</span></span>
<span id="cb53-40"><a href="#cb53-40" aria-hidden="true" tabindex="-1"></a>print.whites.test <span class="ot">&lt;-</span> <span class="cf">function</span>(x, ...) {</span>
<span id="cb53-41"><a href="#cb53-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"White's Test for Heteroskedasticity</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb53-42"><a href="#cb53-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"LM test statistic: "</span>, x<span class="sc">$</span>LM_test_statistic, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb53-43"><a href="#cb53-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"df1: "</span>, x<span class="sc">$</span>df1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb53-44"><a href="#cb53-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"df2: "</span>, x<span class="sc">$</span>df2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb53-45"><a href="#cb53-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"p-value: "</span>, x<span class="sc">$</span>p_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb53-46"><a href="#cb53-46" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (x<span class="sc">$</span>p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>) {</span>
<span id="cb53-47"><a href="#cb53-47" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Heteroskedasticity is present.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb53-48"><a href="#cb53-48" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb53-49"><a href="#cb53-49" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"No significant heteroskedasticity detected.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb53-50"><a href="#cb53-50" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb53-51"><a href="#cb53-51" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4, <span class="at">data =</span> df)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">whites.test</span>(model) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; White's Test for Heteroskedasticity
#&gt; LM test statistic:  1.838336 
#&gt; df1:  14 
#&gt; df2:  12 
#&gt; p-value:  0.1484346 
#&gt; No significant heteroskedasticity detected.</code></pre>
</div>
</div>
<p>If the p-value is small (typically less than 0.05), reject the null hypothesis of homoscedasticity, which means heteroscedasticity is likely present. If White’s test indicates heteroscedasticity, you can use robust standard errors (e.g., <code>vcovHC()</code> function from the <code>sandwich</code> package) to correct for it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use robust standard errors</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(model, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(model, <span class="at">type =</span> <span class="st">"HC3"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>Selection of independent variables: Including too many predictors can lead to overfitting, while excluding important variables can lead to underfitting. Methods like stepwise regression or information criteria (AIC, BIC) can be used to optimize the model.</p></li>
<li><p>Outliers and leverage points: The model is sensitive to outliers and high-leverage points, which can disproportionately influence the results. Use diagnostic tools such as standardized residuals and Cook’s distance to identify and handle these points.</p></li>
<li><p>Linear relationship assumption: The model assumes a linear relationship between independent variables and the dependent variable. If the relationship is non-linear, transformations or polynomial terms may be needed.</p></li>
</ol>
<p>Limitations of Multiple Linear Regression</p>
<ol type="1">
<li>Causality: Regression analysis only shows association, not causation.</li>
<li>Model Interpretability: When there are many predictors, the model may become difficult to interpret, requiring careful variable selection and result explanation.</li>
<li>Extrapolation: The regression model is generally reliable within the range of the data, but predictions outside of this range may be inaccurate.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/qbgaoo\.github\.io\/r4ms");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./multivariate-groups-diff.html" class="pagination-link" aria-label="Multivariate data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multivariate data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./logistic-regression.html" class="pagination-link" aria-label="Logistic regression analysis">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic regression analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://qbgaoo.github.io/r4ms/edit/main/multiple-linear-regression.qmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://qbgaoo.github.io/r4ms/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>