# Quarto

## GitHub Action

There are several different ways to present and publish content. Below, we'll provide a guide to publishing content using [GitHub Actions](https://docs.github.com/en/actions) and GitHub Pages.

### Execute code

If you choose, you can configure a GitHub Action to execute R code as part of the rendering process. While this is an excellent method for automating content rendering, it comes with specific requirements when executing code in CI services like GitHub Actions:

-   You need to reconfigure all dependencies in the CI environment. This includes installing R itself and ensuring the correct versions of all required packages are available.
-    If your code requires special permissions (e.g., access to databases or external networks), these permissions must also be configured on the CI server.
-   Your project might include documentation that cannot be easily executed, such as blog posts written years ago that depend on older versions of packages. To avoid errors, these documents may need to use a “freezing” feature to prevent them from executing during the CI process.

### **Prerequisite**

The best way to ensure that your code can be executed in GitHub Action is to use the [renv](https://rstudio.github.io/renv/articles/renv.html) virtual environment for your project. Here is a complete GitHub Action example that installs package dependencies in R and `renv.lock`, then executes the code and renders the output to GitHub Pages:

::: callout-tip
Run the following Git commands in sequence from the Terminal tab in the lower left window of RStudio

-   git remote add origin https://github.com/qbgaoo/r4ms.git
-   git branch -M main
-   git push -u origin main
:::

In the Quarto project, create a new text file named `publish.yml` (or another name, if preferred). Save it to the path `.github/workflows/publish.yml`, and add the following content to the file:

``` yaml
on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:
  schedule:
    # run every day at 11 PM
    - cron: '0 23 * * *'

name: Render and deploy Book to Github

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This is a GitHub Actions workflow configuration file. After saving it, commit the file to GitHub to trigger the workflow defined within it.
