<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>21&nbsp; Survival analysis – R for Medical Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./cluster-analysis.html" rel="next">
<link href="./generalized-linear-model.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d166b450ba5a8e9f7a0ab969bf6592c1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a5df2f7bee1221c19b681c9ee270b753.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-4fa198ee4e862f6b14ef67ac2231ddcd.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./advanced-stat.html">Advanced methods</a></li><li class="breadcrumb-item"><a href="./survival-analysis.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Survival analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R for Medical Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://qbgaoo.github.io/r4ms" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-git"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./basic-stat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quat-data-statdesc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statistical description of quantitative data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Normal distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Statistical inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-data-statdesc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistical description of count data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discrete-data-dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Distributions of discrete variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chi-square-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chi-square test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonparametric-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Nonparametric Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Bivariate regression and correlation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./advanced-stat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Advanced methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multifactor-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Multifactor ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repeated-measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Repeated measures ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general-linear-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">General linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multivariate-groups-diff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multivariate data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multiple linear regression analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Logistic regression analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./generalized-linear-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Generalized linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Survival analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cluster-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Cluster analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discriminant-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Discriminant analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pca-factor-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Principal components and factor analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./canonical-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Canonical correlation analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./structural-equation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Structural equation model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multilevel-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Multilevel model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comprehensive-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Comprehensive evaluation methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./community-intervention.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Community intervention trials</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scale-develop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Medical scales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./meta-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Meta analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general-estimat-equation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Generalized estimating equation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./practical-skills.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practical skills</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-preprocess.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Random sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Randomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Sample size estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pilot-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">A case to analyze</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./memo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Memo for future programming</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#prerequisite" id="toc-prerequisite" class="nav-link active" data-scroll-target="#prerequisite"><span class="header-section-number">21.1</span> Prerequisite</a></li>
  <li><a href="#basic-concepts" id="toc-basic-concepts" class="nav-link" data-scroll-target="#basic-concepts"><span class="header-section-number">21.2</span> Basic concepts</a>
  <ul class="collapse">
  <li><a href="#time-to-event" id="toc-time-to-event" class="nav-link" data-scroll-target="#time-to-event"><span class="header-section-number">21.2.1</span> Time-to-event</a></li>
  <li><a href="#censoring" id="toc-censoring" class="nav-link" data-scroll-target="#censoring"><span class="header-section-number">21.2.2</span> Censoring</a></li>
  <li><a href="#survival-rate" id="toc-survival-rate" class="nav-link" data-scroll-target="#survival-rate"><span class="header-section-number">21.2.3</span> Survival rate</a></li>
  <li><a href="#hazard-rate" id="toc-hazard-rate" class="nav-link" data-scroll-target="#hazard-rate"><span class="header-section-number">21.2.4</span> Hazard rate</a></li>
  </ul></li>
  <li><a href="#statistical-methods-for-survival-analysis" id="toc-statistical-methods-for-survival-analysis" class="nav-link" data-scroll-target="#statistical-methods-for-survival-analysis"><span class="header-section-number">21.3</span> Statistical methods for survival analysis</a>
  <ul class="collapse">
  <li><a href="#descriptive-analysis" id="toc-descriptive-analysis" class="nav-link" data-scroll-target="#descriptive-analysis"><span class="header-section-number">21.3.1</span> Descriptive analysis</a></li>
  <li><a href="#comparative-analysis" id="toc-comparative-analysis" class="nav-link" data-scroll-target="#comparative-analysis"><span class="header-section-number">21.3.2</span> Comparative analysis</a></li>
  <li><a href="#affecting-factors-analysis" id="toc-affecting-factors-analysis" class="nav-link" data-scroll-target="#affecting-factors-analysis"><span class="header-section-number">21.3.3</span> Affecting factors analysis</a></li>
  </ul></li>
  <li><a href="#estimation-of-survival-rate-and-survival-curve" id="toc-estimation-of-survival-rate-and-survival-curve" class="nav-link" data-scroll-target="#estimation-of-survival-rate-and-survival-curve"><span class="header-section-number">21.4</span> Estimation of survival rate and survival curve</a>
  <ul class="collapse">
  <li><a href="#kaplan-meier-method" id="toc-kaplan-meier-method" class="nav-link" data-scroll-target="#kaplan-meier-method"><span class="header-section-number">21.4.1</span> Kaplan-Meier method</a></li>
  <li><a href="#life-table-method" id="toc-life-table-method" class="nav-link" data-scroll-target="#life-table-method"><span class="header-section-number">21.4.2</span> Life table method</a></li>
  </ul></li>
  <li><a href="#comparison-of-survival-rates" id="toc-comparison-of-survival-rates" class="nav-link" data-scroll-target="#comparison-of-survival-rates"><span class="header-section-number">21.5</span> Comparison of survival rates</a>
  <ul class="collapse">
  <li><a href="#log-rank-test" id="toc-log-rank-test" class="nav-link" data-scroll-target="#log-rank-test"><span class="header-section-number">21.5.1</span> Log-rank test</a></li>
  <li><a href="#breslow-test" id="toc-breslow-test" class="nav-link" data-scroll-target="#breslow-test"><span class="header-section-number">21.5.2</span> Breslow test</a></li>
  </ul></li>
  <li><a href="#cox-proportional-hazards-regression-model" id="toc-cox-proportional-hazards-regression-model" class="nav-link" data-scroll-target="#cox-proportional-hazards-regression-model"><span class="header-section-number">21.6</span> Cox proportional hazards regression model</a>
  <ul class="collapse">
  <li><a href="#equation-of-cox-model" id="toc-equation-of-cox-model" class="nav-link" data-scroll-target="#equation-of-cox-model"><span class="header-section-number">21.6.1</span> Equation of Cox model</a></li>
  <li><a href="#parameter-estimation-and-hypothesis-test" id="toc-parameter-estimation-and-hypothesis-test" class="nav-link" data-scroll-target="#parameter-estimation-and-hypothesis-test"><span class="header-section-number">21.6.2</span> Parameter estimation and hypothesis test</a></li>
  <li><a href="#screening-of-factors" id="toc-screening-of-factors" class="nav-link" data-scroll-target="#screening-of-factors"><span class="header-section-number">21.6.3</span> Screening of factors</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://qbgaoo.github.io/r4ms/edit/main/survival-analysis.qmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://qbgaoo.github.io/r4ms/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./advanced-stat.html">Advanced methods</a></li><li class="breadcrumb-item"><a href="./survival-analysis.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Survival analysis</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Survival analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In the medical field, survival analysis is widely used to study the time from a starting point to the occurrence of an important event, such as death, disease recurrence, or remission. It plays a critical role in analyzing time-to-event data, understanding the relationship between time and event occurrence, especially when some subjects do not experience the event during the study period, resulting in censored data. The core of survival analysis lies in properly handling censored data and time-related event occurrences, in order to effectively estimate survival probabilities and analyze risk factors.</p>
<section id="prerequisite" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="prerequisite"><span class="header-section-number">21.1</span> Prerequisite</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="basic-concepts" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="basic-concepts"><span class="header-section-number">21.2</span> Basic concepts</h2>
<p>Survival data has several distinctive characteristics that differentiate it from other types of data, which make specialized methods necessary for analysis. The key characteristics of survival data include time-to-event data, censored data, non-normal distribution, and multiple covariates that influence survival time. Here is an example used to illustrate these features and related concepts.</p>
<div id="ex21-01" class="example">
<strong>Example 1</strong> 
<p>To estimate the survival time of patients who are HIV-positive, a researcher conducted a clinical follow-up study. The subjects were individuals diagnosed with HIV in a certain city between January 1, 2002, and December 31, 2004. These subjects were followed until they died of AIDS or its complications (with status = 1 for death, and 0 for censored cases). The study cutoff date was December 31, 2008. Additionally, the gender (sex = 1 for male, 0 for female), age (in years), and medication status (drug = 1 for on medication, 0 for not on medication) of each subject were recorded. The data format are shown in <a href="#tbl-hiv-survival" class="quarto-xref">Table&nbsp;<span>21.1</span></a> .</p>
</div>
<div>
<p><a href="datasets/ex21-01.csv" download="ex21-01.csv" class="btn btn-success"> <i class="bi bi-database-fill-down"></i> Download data </a></p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datasets/ex21-01.csv"</span>, <span class="at">show_col_types =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-hiv-survival" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hiv-survival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.1: Survival time and influencing factors of 100 HIV-positive patients
</figcaption>
<div aria-describedby="tbl-hiv-survival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">ID</th>
<th style="text-align: center;">startpoint</th>
<th style="text-align: center;">endpoint</th>
<th style="text-align: center;">time</th>
<th style="text-align: center;">gender</th>
<th style="text-align: center;">age</th>
<th style="text-align: center;">treat</th>
<th style="text-align: center;">status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">2004-10-07</td>
<td style="text-align: center;">2005-08-07</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">2002-06-29</td>
<td style="text-align: center;">2002-07-29</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">2004-08-02</td>
<td style="text-align: center;">2005-01-01</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">2004-04-05</td>
<td style="text-align: center;">2007-02-03</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">2004-10-01</td>
<td style="text-align: center;">2004-10-31</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">2003-12-12</td>
<td style="text-align: center;">2004-01-11</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="time-to-event" class="level3" data-number="21.2.1">
<h3 data-number="21.2.1" class="anchored" data-anchor-id="time-to-event"><span class="header-section-number">21.2.1</span> Time-to-event</h3>
<p>Time-to-event, also known as survival time, refers to the duration from a specified starting point (such as the onset of a condition, diagnosis, or treatment initiation) to the occurrence of a specific event of interest (such as death, disease progression, or recovery).</p>
<blockquote class="blockquote">
<p>In <a href="#ex21-01">Example 1</a>, survival time represents the time from when the patient was diagnosed as HIV-positive (<code>startpoint</code>) until death or censoring (<code>endpoint</code>). The <code>time</code> column in <a href="#tbl-hiv-survival" class="quarto-xref">Table&nbsp;<span>21.1</span></a> indicates the survival time in months for each participant.</p>
<p>For example: patient with ID=1 has a survival time of 10 months, from October 7, 2004, to August 7, 2005.</p>
</blockquote>
<p>The survival times are often non-normally distributed and typically show a skewed distribution. Standard statistical techniques that assume normality are not appropriate for survival data, so specialized models like the Cox proportional hazards model or accelerated failure time models are used instead. Here is the normality test on the variable of survival time in <a href="#ex21-01">Example 1</a> using <code>shapiro.test()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df, time) <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>() <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro.test</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt;  Shapiro-Wilk normality test
#&gt; 
#&gt; data:  pull(select(df, time))
#&gt; W = 0.65927, p-value = 6.682e-14</code></pre>
</div>
</div>
<p>Moreover, survival data typically exhibits heterogeneity, meaning that the time to the event is influenced by multiple factors, such as age, gender, disease stage, or treatment. Covariates need to be incorporated into survival models (e.g., Cox models) to analyze these factors’ impact on survival time.</p>
<p>Survival analysis revolves around time-to-event data, and focuses on estimating the probability that an event has not yet occurred at a certain point in time and identifying factors influencing this time.</p>
</section>
<section id="censoring" class="level3" data-number="21.2.2">
<h3 data-number="21.2.2" class="anchored" data-anchor-id="censoring"><span class="header-section-number">21.2.2</span> Censoring</h3>
<p>The analysis of time-to-event data often involves censoring, where the exact time of the event is unknown for some individuals. Censoring occurs when the event of interest has not happened for some individuals by the end of the study or they are lost to follow-up. This means we only know that the individual survived up to a certain point, but not the exact time of the event. The common types of censoring includes:</p>
<p><strong>Right censoring</strong>: The most common type. It happens when an individual has not experienced the event by the end of the study. For example, a patient participates in a five-year study but is still alive at the end.</p>
<p><strong>Left censoring</strong>: When the event has occurred before the observation, but the exact time is unknown. For example, a patient is diagnosed with a disease but the precise time of infection is unknown.</p>
<p><strong>Interval censoring</strong>: The event occurs within a known time interval, but the exact time is unknown. For example, a patient is diagnosed with a disease between two follow-up visits.</p>
<blockquote class="blockquote">
<p>In <a href="#tbl-hiv-survival" class="quarto-xref">Table&nbsp;<span>21.1</span></a> , the <code>status</code> column indicates whether the event (death) occurred: status = 1 means the patient died during the study (i.e., the event occurred), status = 0 indicates that the patient’s death was not observed, meaning they were censored.</p>
<p>For example, patient with ID=2 has status = 0, meaning the patient did not die by the end of the follow-up period, making this case censored data.</p>
</blockquote>
</section>
<section id="survival-rate" class="level3" data-number="21.2.3">
<h3 data-number="21.2.3" class="anchored" data-anchor-id="survival-rate"><span class="header-section-number">21.2.3</span> Survival rate</h3>
<p>The survival rate refers to the proportion of individuals who survive for a specific period of time. It is typically expressed as the percentage of individuals who are still alive at a given time interval. For example, a 5-year survival rate of 80% means that 80% of patients are still alive 5 years after diagnosis or treatment.</p>
<p>Survival rate can be derived from the survival function. The survival function, denoted as <span class="math inline">S(t)</span>, is a continuous function that gives the probability of an individual surviving beyond a specific time <span class="math inline">t</span>. It is the key concept in survival analysis and shows how the probability of survival decreases over time. Mathematically, <span class="math inline">S(t)</span> is defined as:</p>
<p><span class="math display">
S(t) = P(T &gt; t)
</span></p>
<p>where <span class="math inline">T</span> is the time to the event (e.g., death), and <span class="math inline">t</span> is a specific time point. For example, if <span class="math inline">S(5) = 0.80</span>, this means that 80% of the individuals are expected to survive beyond 5 years. The survival function is typically visualized using a Kaplan-Meier curve, which plots the probability of survival against time. The curve generally starts at 1 (100% survival) and declines as time increases.</p>
</section>
<section id="hazard-rate" class="level3" data-number="21.2.4">
<h3 data-number="21.2.4" class="anchored" data-anchor-id="hazard-rate"><span class="header-section-number">21.2.4</span> Hazard rate</h3>
<p>The hazard rate, also known as the instantaneous failure rate, describes the likelihood (or risk) that an event (e.g., death or failure) will occur at a particular instant, given that the individual has survived up to that point. It measures the “risk” at a specific time.</p>
<p>For instance, if you have survived 5 years, the hazard rate at that moment tells you how likely it is that you will experience the event (e.g., death) in the next moment of time. The hazard rate has the units of “events per unit time.” It can be interpreted as the instantaneous rate of event occurrence at a certain time.</p>
<p>The hazard function, denoted as <span class="math inline">h(t)</span>, is a continuous function that gives the hazard rate at any given time <span class="math inline">t</span>. It provides the instantaneous rate at which events happen at time <span class="math inline">t</span>, conditional on the fact that the individual has survived until that time. Mathematically, the hazard function is defined as:</p>
<p><span class="math display">
h(t) = \lim_{\Delta t \to 0} \frac{P(t \leq T &lt; t + \Delta t \mid T \geq t)}{\Delta t}
</span></p>
<p>where <span class="math inline">T</span> is the time to the event.</p>
<p>For example, if the hazard function <span class="math inline">h(t) = 0.02</span> at time <span class="math inline">t = 5</span> , this means the instantaneous risk of the event occurring at year 5 is <span class="math inline">2\%</span> per unit of time, given that the subject has survived up to that point.</p>
<p>The survival function <span class="math inline">S(t)</span> is related to the hazard function. In fact, the hazard function can be used to derive the survival function:</p>
<p><span class="math display">S(t) = \exp\left(-\int_0^t h(u) du \right)</span></p>
<p>This shows that the survival function decreases as the hazard function increases. A higher hazard implies a greater risk of event occurrence, leading to a lower probability of survival.</p>
<p>The cumulative hazard function <span class="math inline">H(t)</span> is the integral of the hazard function over time:</p>
<p><span class="math display">
H(t) = \int_0^t h(u) du
</span></p>
<p>It represents the total risk accumulated up to time <span class="math inline">t</span>.</p>
</section>
</section>
<section id="statistical-methods-for-survival-analysis" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="statistical-methods-for-survival-analysis"><span class="header-section-number">21.3</span> Statistical methods for survival analysis</h2>
<p>Statistical methods for survival analysis are primarily used to process time-to-event data and analyze factors related to survival time. This type of data is characterized by the possibility of censoring, in which events for some individuals did not occur at the end of the study.</p>
<section id="descriptive-analysis" class="level3" data-number="21.3.1">
<h3 data-number="21.3.1" class="anchored" data-anchor-id="descriptive-analysis"><span class="header-section-number">21.3.1</span> Descriptive analysis</h3>
<p>Descriptive analysis of survival data aims to summarize and present the basic characteristics of survival time using median survival time, survival rates, event rates, and censored data proportions.</p>
<ol type="1">
<li><p><strong>Kaplan-Meier curve</strong></p>
<p>The Kaplan-Meier curve is a widely used non-parametric method to estimate and plot the survival function <span class="math inline">S(t)</span>, representing the probability of survival over time. It handles censored data and calculates survival probabilities at each event time, showing survival rates at different time points.</p></li>
<li><p><strong>Median survival time</strong></p>
<p>Median survival time is the time at which 50% of the individuals have experienced the event (e.g., death), and the other 50% are still surviving. It is more representative than the mean for skewed data and is not affected by extreme values. For example, if the median survival time for HIV-positive patients is 24 months, it means half of the patients die within 24 months of follow-up.</p></li>
<li><p><strong>Event rate</strong></p>
<p>The event rate reports how many individuals experience the event of interest (e.g., death) during the study and provides an overall summary of the event occurrences. For instance, in a study with 120 patients, if 30 patients die during follow-up, the event rate is 25%.</p></li>
<li><p><strong>Description of censored data</strong></p>
<p>Descriptive analysis of censored data includes reporting the proportion of censored individuals and the distribution of censoring times. This helps understand how many individuals did not experience the event within the study period. In a clinical study with a 5-year follow-up, if 40% of patients are still alive at the end of the study, their survival data are considered censored.</p></li>
<li><p><strong>Distribution of censoring time</strong></p>
<p>Describing the distribution of censoring times helps researchers understand when censoring occurs in the study. This can reveal whether censoring happens early, mid, or late in the study period. If there is heavy censoring early in the study, it may indicate inadequate follow-up or incomplete participation by individuals.</p></li>
</ol>
</section>
<section id="comparative-analysis" class="level3" data-number="21.3.2">
<h3 data-number="21.3.2" class="anchored" data-anchor-id="comparative-analysis"><span class="header-section-number">21.3.2</span> Comparative analysis</h3>
<p>Comparative analysis methods are used to assess the impact of different groups or variables on survival time. Here are some commonly used methods for comparative analysis of survival data:</p>
<ol type="1">
<li><p><strong>Kaplan-Meier</strong> <strong>method</strong></p>
<p>The Kaplan-Meier method is a widely used approach for comparing the survival outcomes of different groups by estimating and plotting survival curves.</p>
<p>It is commonly used to compare survival rates among patients with different treatments or characteristics (e.g., gender) by generating and displaying survival curves.</p></li>
<li><p><strong>Log-rank test</strong></p>
<p>The Log-rank test is a non-parametric test used to compare the survival curves of two or more groups. It compares the number of events and the number of individuals at risk at each time point, assessing whether there are significant differences between the survival distributions of different groups.</p>
<p>It is often used in conjunction with Kaplan-Meier survival curves to determine if there are statistically significant differences in survival rates between treatment groups.</p></li>
<li><p><strong>Hazard ratios comparison</strong></p>
<p>Hazard ratios (HR) provide a measure for comparing the survival risks between different groups. HR can be estimated using the Cox model. For example, if HR = 1.5, it indicates that the mortality risk in group A is 1.5 times that of group B, offering a quantitative comparison of survival risk between groups.</p></li>
<li><p><strong>Survival function comparison</strong></p>
<p>This method involves directly comparing the survival functions of different groups (e.g., using Kullback-Leibler divergence) to assess differences in survival distributions. Comparing survival functions helps identify which groups have higher survival probabilities at specific time points.</p></li>
</ol>
</section>
<section id="affecting-factors-analysis" class="level3" data-number="21.3.3">
<h3 data-number="21.3.3" class="anchored" data-anchor-id="affecting-factors-analysis"><span class="header-section-number">21.3.3</span> Affecting factors analysis</h3>
<p>Analyzing the factors affecting survival data is crucial for assessing how various covariates influence survival time. Here are some commonly used methods for this type of analysis:</p>
<ol type="1">
<li><p><strong>Cox proportional hazards model</strong></p>
<p>The Cox proportional hazards model is a semi-parametric model used to analyze the relationship between survival data and multiple covariates. This model assumes that the effect of covariates on the hazard ratio is constant over time, allowing for the estimation of hazard ratios to compare survival times across different groups.</p>
<p>It is used to assess the impact of various factors (e.g., age, gender, treatment) on survival time and to perform multivariate analyses.</p></li>
<li><p><strong>Kaplan-Meier analysis with covariates</strong></p>
<p>Incorporating covariates in Kaplan-Meier analysis allows for exploring survival differences among groups. Survival curves are generated for different groups based on covariates (e.g., treatment groups, age) and compared visually.</p>
<p>This approach helps to illustrate survival rates across different groups and can be complemented by the Log-rank test for statistical comparison.</p></li>
<li><p><strong>Multivariate analysis</strong></p>
<p>Multivariate analysis allows for the simultaneous consideration of multiple covariates affecting survival time. This can include using the Cox model or weighted survival regression to control for several covariates.</p>
<p>It assesses how multiple factors collectively influence survival time, such as evaluating the impact of age, gender, and treatment on patient survival.</p></li>
<li><p><strong>Survival trees and random forests</strong></p>
<p>Survival trees and random forests are tree-based non-parametric methods capable of handling high-dimensional data and nonlinear relationships. These models construct tree-like structures to partition the data, identifying key variables affecting survival time. These methods are useful for feature selection and modeling complex interactions.</p></li>
<li><p><strong>Bayesian survival analysis</strong></p>
<p>Bayesian survival analysis employs Bayesian methods to handle survival data, allowing for the incorporation of prior knowledge into the analysis. This method is beneficial for conducting uncertainty analysis and posterior predictions, particularly in small sample settings or complex models.</p></li>
</ol>
</section>
</section>
<section id="estimation-of-survival-rate-and-survival-curve" class="level2" data-number="21.4">
<h2 data-number="21.4" class="anchored" data-anchor-id="estimation-of-survival-rate-and-survival-curve"><span class="header-section-number">21.4</span> Estimation of survival rate and survival curve</h2>
<p>Estimating survival rates is essential for determining the proportion of individuals who survive over a specified period. Here are some commonly used methods for estimating survival rates:</p>
<section id="kaplan-meier-method" class="level3" data-number="21.4.1">
<h3 data-number="21.4.1" class="anchored" data-anchor-id="kaplan-meier-method"><span class="header-section-number">21.4.1</span> Kaplan-Meier method</h3>
<p>The Kaplan-Meier method, also known as the product-limit method, is a non-parametric method used to estimate the survival function from survival data. It accounts for censored data and adjusts the survival probability at each event occurrence. The survival probability is computed as:</p>
<p><span class="math display">
\hat{S}(t) = \prod_{i: t_i \leq t} \left( 1 - \frac{d_i}{n_i} \right)
</span></p>
<p>where <span class="math inline">t_i</span> = the event time (time at which an event occurs), <span class="math inline">d_i</span> = the number of events (e.g., deaths) at time <span class="math inline">t_i</span>, <span class="math inline">n_i</span> = the number of individuals at risk just before time <span class="math inline">t_i</span>.</p>
<div id="ex21-02" class="example">
<strong>Example 2</strong> 
<p>To compare the efficacy of different surgical methods for treating adrenal tumors, a researcher randomly divided 43 patients into two groups: 23 in group A and 20 in group B. The survival times (in months) for each group are shown in the table below. Calculate the survival rate.</p>
</div>
<div>
<p><a href="datasets/ex21-02.csv" download="ex20-02.csv" class="btn btn-success"> <i class="bi bi-database-fill-down"></i> Download data </a></p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>tb <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datasets/ex21-02.csv"</span>, <span class="at">show_col_types =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">14+</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">19+</td>
<td style="text-align: center;">20+</td>
<td style="text-align: center;">22+</td>
<td style="text-align: center;">26+</td>
<td style="text-align: center;">31+</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">34+</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">59</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The <code>survfit()</code> function from the <code>survival</code> package is commonly used to estimate survival rates. The <code>Surv()</code> function creates a survival object, usually used as a response variable in a model formula. Here’s an example of basic usage:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-5"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><button class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="1">1</button><span id="annotated-cell-5-1" class="code-annotation-target"><a href="#annotated-cell-5-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, <span class="at">event =</span> status) <span class="sc">~</span> group, <span class="at">data =</span> tb)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="2">2</button><span id="annotated-cell-5-2" class="code-annotation-target"><a href="#annotated-cell-5-2" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">|&gt;</span> <span class="fu">summary</span>(<span class="at">censored =</span> T)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-5" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="1" data-code-annotation="1">Instead of specifying ~ group in the model formula, which would compare survival between groups, you can use ~ 1 for a single group.</span>
</dd>
<dt data-target-cell="annotated-cell-5" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="2" data-code-annotation="2">By default, the <code>summary()</code> function for survfit objects only outputs a summary at distinct time points where events occur. If you want to show times for censored events as well, set <code>censored = T</code>.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Call: survfit(formula = Surv(time, event = status) ~ group, data = tb)
#&gt; 
#&gt;                 group=1 
#&gt;  time n.risk n.event survival std.err lower 95% CI upper 95% CI
#&gt;     1     23       1    0.957  0.0425       0.8767        1.000
#&gt;     3     22       1    0.913  0.0588       0.8049        1.000
#&gt;     5     21       3    0.783  0.0860       0.6310        0.971
#&gt;     6     18       3    0.652  0.0993       0.4839        0.879
#&gt;     7     15       1    0.609  0.1018       0.4386        0.845
#&gt;     8     14       1    0.565  0.1034       0.3950        0.809
#&gt;    10     13       2    0.478  0.1042       0.3121        0.733
#&gt;    14     11       0    0.478  0.1042       0.3121        0.733
#&gt;    17     10       1    0.430  0.1041       0.2679        0.692
#&gt;    19      9       0    0.430  0.1041       0.2679        0.692
#&gt;    20      8       0    0.430  0.1041       0.2679        0.692
#&gt;    22      7       0    0.430  0.1041       0.2679        0.692
#&gt;    26      6       0    0.430  0.1041       0.2679        0.692
#&gt;    31      5       0    0.430  0.1041       0.2679        0.692
#&gt;    34      4       1    0.323  0.1216       0.1543        0.675
#&gt;    44      2       1    0.161  0.1293       0.0336        0.776
#&gt;    59      1       1    0.000     NaN           NA           NA
#&gt; 
#&gt;                 group=2 
#&gt;  time n.risk n.event survival std.err lower 95% CI upper 95% CI
#&gt;     1     20       2     0.90  0.0671       0.7777        1.000
#&gt;     2     18       1     0.85  0.0798       0.7071        1.000
#&gt;     3     17       2     0.75  0.0968       0.5823        0.966
#&gt;     4     15       3     0.60  0.1095       0.4195        0.858
#&gt;     6     12       2     0.50  0.1118       0.3226        0.775
#&gt;     8     10       1     0.45  0.1112       0.2772        0.731
#&gt;     9      9       2     0.35  0.1067       0.1926        0.636
#&gt;    10      7       1     0.30  0.1025       0.1536        0.586
#&gt;    11      6       1     0.25  0.0968       0.1170        0.534
#&gt;    12      5       1     0.20  0.0894       0.0832        0.481
#&gt;    13      4       1     0.15  0.0798       0.0528        0.426
#&gt;    15      3       1     0.10  0.0671       0.0269        0.372
#&gt;    17      2       1     0.05  0.0487       0.0074        0.338
#&gt;    18      1       1     0.00     NaN           NA           NA</code></pre>
</div>
</div>
<p>The <code>summary()</code> output returns a list containing the survival rate, confidence limits for the rates, and other information.</p>
<p>You can use the code below to get the median survival time:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">|&gt;</span> <span class="fu">median</span>() <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">"term"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">"term"</span>, <span class="st">"median"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 2 × 2
#&gt;   term    median
#&gt;   &lt;chr&gt;    &lt;dbl&gt;
#&gt; 1 group=1     10
#&gt; 2 group=2      7</code></pre>
</div>
</div>
<p>The <code>ggsurvplot()</code> function from <code>survminer</code> package is designed to directly plot survival curves. It’s a convenient function that creates publication-ready survival curves.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  fit,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Time(month)"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Survival Probability"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pval =</span> T,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pval.size =</span> <span class="fl">3.8</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">censor.shape =</span> <span class="dv">1</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">censor.size =</span> <span class="dv">2</span>, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">0.8</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title =</span> <span class="st">""</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.labs =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#E7B800"</span>, <span class="st">"#2E9FDF"</span>),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> <span class="fl">0.5</span>,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.x =</span> <span class="dv">9</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.y =</span> <span class="dv">9</span>,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.tickslab =</span> <span class="dv">9</span>,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.legend =</span> <span class="dv">9</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="survival-analysis_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="life-table-method" class="level3" data-number="21.4.2">
<h3 data-number="21.4.2" class="anchored" data-anchor-id="life-table-method"><span class="header-section-number">21.4.2</span> Life table method</h3>
<p>Life tables are a classic method for estimating survival rates by dividing individuals into different age groups or time intervals. This method calculates survival rates based on the number of deaths and survivors in each age group. It is commonly used in public health and epidemiological studies to estimate the survival probability of specific populations.</p>
<div class="example">
<strong>Example 3</strong> 
<p>A researcher followed up and collected data on 2,418 male angina patients in a certain region. The organized data is presented in Table 18-6. Please calculate the survival rate for male angina patients in this region.</p>
</div>
<div>
<p><a href="datasets/ex21-03.csv" download="ex21-03.csv" class="btn btn-success"> <i class="bi bi-database-fill-down"></i> Download data </a></p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tb <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datasets/ex21-03.csv"</span>, <span class="at">show_col_types =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>life_df <span class="ot">&lt;-</span> tb <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">censor =</span> <span class="fu">factor</span>(censor, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"event"</span>, <span class="st">"censor"</span>))) <span class="sc">|&gt;</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> <span class="fu">c</span>(censor),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_prefix =</span> <span class="st">"n."</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> freq</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To calculate the survival rates using life tables, you can use the <code>lifetab()</code> function from <code>KMsurv</code> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-10"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-10-1"><a href="#annotated-cell-10-1" aria-hidden="true" tabindex="-1"></a>surv_rlt <span class="ot">&lt;-</span> life_df <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-10-2"><a href="#annotated-cell-10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(KMsurv<span class="sc">::</span><span class="fu">lifetab</span>(</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="1">1</button><span id="annotated-cell-10-3" class="code-annotation-target"><a href="#annotated-cell-10-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">tis =</span> <span class="fu">c</span>(time, <span class="dv">16</span>),</span>
<span id="annotated-cell-10-4"><a href="#annotated-cell-10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ninit =</span> <span class="fu">sum</span>(n.event <span class="sc">+</span> n.censor),</span>
<span id="annotated-cell-10-5"><a href="#annotated-cell-10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">nlost =</span> n.censor,</span>
<span id="annotated-cell-10-6"><a href="#annotated-cell-10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">nevent =</span> n.event</span>
<span id="annotated-cell-10-7"><a href="#annotated-cell-10-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="annotated-cell-10-8"><a href="#annotated-cell-10-8" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="annotated-cell-10-9"><a href="#annotated-cell-10-9" aria-hidden="true" tabindex="-1"></a>surv_rlt <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">align =</span> <span class="st">"c"</span>, <span class="at">digits =</span> <span class="dv">5</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-10" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-10" data-code-lines="3" data-code-annotation="1">Length of tis is 1 greater than nlost and nevent.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">nsubs</th>
<th style="text-align: center;">nlost</th>
<th style="text-align: center;">nrisk</th>
<th style="text-align: center;">nevent</th>
<th style="text-align: center;">surv</th>
<th style="text-align: center;">pdf</th>
<th style="text-align: center;">hazard</th>
<th style="text-align: center;">se.surv</th>
<th style="text-align: center;">se.pdf</th>
<th style="text-align: center;">se.hazard</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0-1</td>
<td style="text-align: center;">2418</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2418.0</td>
<td style="text-align: center;">456</td>
<td style="text-align: center;">1.00000</td>
<td style="text-align: center;">0.18859</td>
<td style="text-align: center;">0.20822</td>
<td style="text-align: center;">0.00000</td>
<td style="text-align: center;">0.00796</td>
<td style="text-align: center;">0.00970</td>
</tr>
<tr class="even">
<td style="text-align: left;">1-2</td>
<td style="text-align: center;">1962</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">1942.5</td>
<td style="text-align: center;">226</td>
<td style="text-align: center;">0.81141</td>
<td style="text-align: center;">0.09440</td>
<td style="text-align: center;">0.12353</td>
<td style="text-align: center;">0.00796</td>
<td style="text-align: center;">0.00598</td>
<td style="text-align: center;">0.00820</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2-3</td>
<td style="text-align: center;">1697</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">1686.0</td>
<td style="text-align: center;">152</td>
<td style="text-align: center;">0.71701</td>
<td style="text-align: center;">0.06464</td>
<td style="text-align: center;">0.09441</td>
<td style="text-align: center;">0.00918</td>
<td style="text-align: center;">0.00507</td>
<td style="text-align: center;">0.00765</td>
</tr>
<tr class="even">
<td style="text-align: left;">3-4</td>
<td style="text-align: center;">1523</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">1511.5</td>
<td style="text-align: center;">171</td>
<td style="text-align: center;">0.65237</td>
<td style="text-align: center;">0.07380</td>
<td style="text-align: center;">0.11992</td>
<td style="text-align: center;">0.00973</td>
<td style="text-align: center;">0.00543</td>
<td style="text-align: center;">0.00915</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4-5</td>
<td style="text-align: center;">1329</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">1317.0</td>
<td style="text-align: center;">135</td>
<td style="text-align: center;">0.57856</td>
<td style="text-align: center;">0.05931</td>
<td style="text-align: center;">0.10804</td>
<td style="text-align: center;">0.01014</td>
<td style="text-align: center;">0.00495</td>
<td style="text-align: center;">0.00929</td>
</tr>
<tr class="even">
<td style="text-align: left;">5-6</td>
<td style="text-align: center;">1170</td>
<td style="text-align: center;">107</td>
<td style="text-align: center;">1116.5</td>
<td style="text-align: center;">125</td>
<td style="text-align: center;">0.51926</td>
<td style="text-align: center;">0.05813</td>
<td style="text-align: center;">0.11860</td>
<td style="text-align: center;">0.01030</td>
<td style="text-align: center;">0.00503</td>
<td style="text-align: center;">0.01059</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6-7</td>
<td style="text-align: center;">938</td>
<td style="text-align: center;">133</td>
<td style="text-align: center;">871.5</td>
<td style="text-align: center;">83</td>
<td style="text-align: center;">0.46112</td>
<td style="text-align: center;">0.04392</td>
<td style="text-align: center;">0.10000</td>
<td style="text-align: center;">0.01038</td>
<td style="text-align: center;">0.00469</td>
<td style="text-align: center;">0.01096</td>
</tr>
<tr class="even">
<td style="text-align: left;">7-8</td>
<td style="text-align: center;">722</td>
<td style="text-align: center;">102</td>
<td style="text-align: center;">671.0</td>
<td style="text-align: center;">74</td>
<td style="text-align: center;">0.41721</td>
<td style="text-align: center;">0.04601</td>
<td style="text-align: center;">0.11672</td>
<td style="text-align: center;">0.01045</td>
<td style="text-align: center;">0.00518</td>
<td style="text-align: center;">0.01355</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8-9</td>
<td style="text-align: center;">546</td>
<td style="text-align: center;">68</td>
<td style="text-align: center;">512.0</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">0.37120</td>
<td style="text-align: center;">0.03697</td>
<td style="text-align: center;">0.10483</td>
<td style="text-align: center;">0.01058</td>
<td style="text-align: center;">0.00502</td>
<td style="text-align: center;">0.01466</td>
</tr>
<tr class="even">
<td style="text-align: left;">9-10</td>
<td style="text-align: center;">427</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">395.0</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">0.33422</td>
<td style="text-align: center;">0.03554</td>
<td style="text-align: center;">0.11230</td>
<td style="text-align: center;">0.01072</td>
<td style="text-align: center;">0.00531</td>
<td style="text-align: center;">0.01730</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10-11</td>
<td style="text-align: center;">321</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">298.5</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">0.29868</td>
<td style="text-align: center;">0.04303</td>
<td style="text-align: center;">0.15523</td>
<td style="text-align: center;">0.01089</td>
<td style="text-align: center;">0.00627</td>
<td style="text-align: center;">0.02360</td>
</tr>
<tr class="even">
<td style="text-align: left;">11-12</td>
<td style="text-align: center;">233</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">206.5</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">0.25566</td>
<td style="text-align: center;">0.04209</td>
<td style="text-align: center;">0.17942</td>
<td style="text-align: center;">0.01112</td>
<td style="text-align: center;">0.00685</td>
<td style="text-align: center;">0.03065</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12-13</td>
<td style="text-align: center;">146</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">129.5</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">0.21356</td>
<td style="text-align: center;">0.02968</td>
<td style="text-align: center;">0.14938</td>
<td style="text-align: center;">0.01140</td>
<td style="text-align: center;">0.00668</td>
<td style="text-align: center;">0.03511</td>
</tr>
<tr class="even">
<td style="text-align: left;">13-14</td>
<td style="text-align: center;">95</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">81.5</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">0.18388</td>
<td style="text-align: center;">0.02031</td>
<td style="text-align: center;">0.11688</td>
<td style="text-align: center;">0.01177</td>
<td style="text-align: center;">0.00651</td>
<td style="text-align: center;">0.03889</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14-15</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">42.5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.16357</td>
<td style="text-align: center;">0.02309</td>
<td style="text-align: center;">0.15190</td>
<td style="text-align: center;">0.01226</td>
<td style="text-align: center;">0.00891</td>
<td style="text-align: center;">0.06183</td>
</tr>
<tr class="even">
<td style="text-align: left;">15-16</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">10.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.14048</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">0.01368</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>You can visualize the survival curve using <code>ggplot2</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> life_df<span class="sc">$</span>time,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">surv.rate =</span> surv_rlt<span class="sc">$</span>surv</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(time, surv.rate)) <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time"</span>, <span class="at">y =</span> <span class="st">"Survival Probability"</span>, <span class="at">font =</span> <span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="survival-analysis_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="comparison-of-survival-rates" class="level2" data-number="21.5">
<h2 data-number="21.5" class="anchored" data-anchor-id="comparison-of-survival-rates"><span class="header-section-number">21.5</span> Comparison of survival rates</h2>
<p>The comparison of survival rates in survival analysis is often done to evaluate whether the survival experiences of two or more groups differ significantly. There are various statistical methods available to compare survival rates across groups. Here’s an outline of common methods used for comparing survival rates:</p>
<div class="example">
<strong>Example 4</strong> 
<p>Based on the data from <a href="#ex21-02">Example 2</a>, compare the survival rates between the two surgical methods, A and B, to determine if there is a significant difference.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>tb <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datasets/ex21-02.csv"</span>, <span class="at">show_col_types =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="log-rank-test" class="level3" data-number="21.5.1">
<h3 data-number="21.5.1" class="anchored" data-anchor-id="log-rank-test"><span class="header-section-number">21.5.1</span> Log-rank test</h3>
<p>Log-rank test, also known as Mantel-Cox test, is the most commonly used method to compare survival rates between two or more groups. It compares the observed events with the expected number of events under the assumption that the survival experiences are the same for all groups. The log-rank test is used when you want to test whether two or more groups have the same survival distribution.</p>
<p>You can run th log-rank test using the <code>survdiff()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> group, <span class="at">data =</span> tb) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Call:
#&gt; survdiff(formula = Surv(time, status) ~ group, data = tb)
#&gt; 
#&gt;          N Observed Expected (O-E)^2/E (O-E)^2/V
#&gt; group=1 23       16     23.8      2.56      8.75
#&gt; group=2 20       20     12.2      5.00      8.75
#&gt; 
#&gt;  Chisq= 8.8  on 1 degrees of freedom, p= 0.003</code></pre>
</div>
</div>
</section>
<section id="breslow-test" class="level3" data-number="21.5.2">
<h3 data-number="21.5.2" class="anchored" data-anchor-id="breslow-test"><span class="header-section-number">21.5.2</span> Breslow test</h3>
<p>Breslow test, also known as generalized Wilcoxon test or Gehan-Wilcoxon test, is a non-parametric test used to compare the survival distributions of two or more groups in survival analysis. It is similar to the log-rank test, but it gives more weight to events that occur at earlier time points. This makes the Breslow test particularly useful when you expect survival differences to be more pronounced early in the study period.</p>
<p>You can run the Breslow test using the <code>survdiff()</code> function from the survival package by specifying the rho argument as 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> group, <span class="at">data =</span> tb, <span class="at">rho =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Call:
#&gt; survdiff(formula = Surv(time, status) ~ group, data = tb, rho = 1)
#&gt; 
#&gt;          N Observed Expected (O-E)^2/E (O-E)^2/V
#&gt; group=1 23     9.15    13.41      1.35       5.2
#&gt; group=2 20    12.69     8.43      2.15       5.2
#&gt; 
#&gt;  Chisq= 5.2  on 1 degrees of freedom, p= 0.02</code></pre>
</div>
</div>
</section>
</section>
<section id="cox-proportional-hazards-regression-model" class="level2" data-number="21.6">
<h2 data-number="21.6" class="anchored" data-anchor-id="cox-proportional-hazards-regression-model"><span class="header-section-number">21.6</span> Cox proportional hazards regression model</h2>
<p>The Cox proportional hazards regression model, often referred to as the Cox model, is a commonly used method in survival analysis to assess the effect of several variables on the survival time. It models the relationship between covariates and the hazard function, which describes the risk of an event (such as death or failure) occurring at a given time.</p>
<p>The Cox model does not require the survival times to follow a specific probability distribution. The ratio of hazards between groups remains constant over time. This model can effectively account for right-censored data.</p>
<section id="equation-of-cox-model" class="level3" data-number="21.6.1">
<h3 data-number="21.6.1" class="anchored" data-anchor-id="equation-of-cox-model"><span class="header-section-number">21.6.1</span> Equation of Cox model</h3>
<p>The Cox model expresses the hazard for an subject at time <span class="math inline">t</span>, given a set of covariates <span class="math inline">X</span>, as:</p>
<p><span class="math display">
h(t|X) = h_0(t) \cdot \exp(\beta_1 X_1 + \beta_2 X_2 + … + \beta_p X_p)
</span></p>
<p>where <span class="math inline">h_0(t)</span> is the baseline hazard at time <span class="math inline">t</span>, <span class="math inline">\beta_1, \beta_2, …, \beta_p</span> are the regression coefficients corresponding to covariates <span class="math inline">X_1, X_2, …, X_p</span>.</p>
</section>
<section id="parameter-estimation-and-hypothesis-test" class="level3" data-number="21.6.2">
<h3 data-number="21.6.2" class="anchored" data-anchor-id="parameter-estimation-and-hypothesis-test"><span class="header-section-number">21.6.2</span> Parameter estimation and hypothesis test</h3>
<p>In the Cox model, estimating parameters and conducting hypothesis tests are critical steps for understanding the relationships between covariates and survival outcomes.</p>
<p><strong>Parameter estimation</strong></p>
<p>The Cox model estimates the regression coefficients (denoted by <span class="math inline">\beta</span>) using partial likelihood estimation. Unlike traditional regression models that use maximum likelihood, the Cox model’s partial likelihood method focuses only on the ordering of event times and does not require specifying the baseline hazard function <span class="math inline">h_0(t)</span>.</p>
<p>For a set of n individuals, suppose that at time <span class="math inline">t_i</span> one individual experiences an event, while the others are either still alive or censored. The partial likelihood for the Cox model is based on the probability that the event occurs to individual i , given that it occurs to one of the individuals still at risk at time t_i .</p>
<p>The partial likelihood function <span class="math inline">L(\beta)</span> for the Cox model is given by:</p>
<p><span class="math display">
L(\beta) = \prod_{i \in \text{events}} \frac{\exp(\beta^T X_i)}{\sum_{j \in \text{risk set at time } t_i} \exp(\beta^T X_j)}
</span></p>
<p>where <span class="math inline">X_i</span> is the covariate vector for individual <span class="math inline">i</span>. The denominator is the sum of the covariate effects of all individuals still at risk at time <span class="math inline">t_i</span>. The parameters <span class="math inline">\beta</span> are estimated by maximizing the partial likelihood <span class="math inline">L(\beta)</span>, which provides estimates of the log-hazard ratios for each covariate.</p>
<p><strong>Hypothesis test</strong></p>
<p>Once the model is fit and the coefficients <span class="math inline">\beta</span> are estimated, hypothesis test is used to assess the significance of each covariate in the model. Similar to logistic regression, commonly used regression coefficient hypothesis test methods include likelihood ratio test, Wald test and score test, as discussed in <a href="logistic-regression.html" class="quarto-xref"><span>Chapter 19</span></a> .</p>
</section>
<section id="screening-of-factors" class="level3" data-number="21.6.3">
<h3 data-number="21.6.3" class="anchored" data-anchor-id="screening-of-factors"><span class="header-section-number">21.6.3</span> Screening of factors</h3>
<p>In a Cox model, selecting influential factors and establishing the best model are crucial steps to identify variables significantly associated with survival time and to construct a simplified model with strong predictive capability. Below is an overview of the methods and steps involved:</p>
<p><strong>Initial screening of factors</strong></p>
<p>When building a Cox model, common methods for preliminary variable screening include univariate analysis and correlation analysis.</p>
<ol type="1">
<li><p><strong>Univariate analysis</strong></p>
<p>Start by using univariate Cox regression models to assess the individual association between each variable and survival time. By fitting univariate Cox models, you can determine which variables may have a significant effect on survival time. The log-rank test can also be used for analysis of categorical covariates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> covariate, <span class="at">data =</span> tb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Focus on the p-values (typically, p &lt; 0.05 is considered significant) to identify variables related to survival time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(var1, var2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Correlation analysis</strong></p>
<p>For cases where there may be multicollinearity between variables, correlation analysis (Pearson or Spearman correlation) can be used to assess relationships between variables, avoiding the inclusion of highly correlated variables in the model to prevent overfitting.</p></li>
</ol>
<p><strong>Stepwise regression</strong></p>
<p>After the initial screening, stepwise regression can be used to automatically select the best model. This method adds or removes variables step-by-step, ultimately selecting those that have a significant effect on survival time, leading to a simplified and accurate model.</p>
<p>The <code>step()</code> function is used for stepwise regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the full model</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> var1 <span class="sc">+</span> var2 <span class="sc">+</span> var3, <span class="at">data =</span> tb)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use AIC for stepwise regression</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>best_model <span class="ot">&lt;-</span> <span class="fu">step</span>(full_model, <span class="at">direction =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Stepwise regression selects the model with the lowest AIC, as a lower AIC indicates a better fit.</p>
<p><strong>LASSO and RIDGE regression</strong></p>
<p>For cases with many variables, LASSO or RIDGE regression can be used for variable selection. LASSO regression applies an <span class="math inline">L_1</span> norm penalty to shrink some coefficients to zero, effectively selecting variables. RIDGE regression applies an <span class="math inline">L_2</span> norm penalty to prevent overfitting, though it doesn’t shrink coefficients to zero.</p>
<p>The <code>glmnet</code> package is used for LASSO and Ridge regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> var1 <span class="sc">+</span> var2 <span class="sc">+</span> var3, <span class="at">data =</span> tb)[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">Surv</span>(tb<span class="sc">$</span>time, tb<span class="sc">$</span>status)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># LASSO regression (alpha=1)</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>lasso_model <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X, y, <span class="at">family =</span> <span class="st">"cox"</span>, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the best model's coefficients</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lasso_model, <span class="at">s =</span> <span class="st">"lambda.min"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Model evaluation</strong></p>
<p>After selecting the best model, it’s important to evaluate the model to ensure it fits well and has good predictive ability. Common evaluation methods include:</p>
<ol type="1">
<li><p><strong>C-Statistic (C-index)</strong></p>
<p>The C-statistic evaluates the model’s ability to distinguish between different survival times. Values range between 0.5 and 1, with values closer to 1 indicating better predictive ability.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>survival<span class="sc">::</span><span class="fu">concordance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Residual analysis</strong></p>
<p>Schoenfeld residuals can be used to test whether the proportional hazards assumption holds for the Cox model. If the assumption is violated, time-dependent covariates may be needed to correct the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cox_test <span class="ot">&lt;-</span> <span class="fu">cox.zph</span>(best_model)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>cox_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output of <code>cox.zph()</code> provides both statistical tests and diagnostic plots for each covariate in the Cox model.</p>
<p>Global test: This tests the overall proportional hazards assumption for the entire model. If this test is significant (p &lt; 0.05), it suggests that the assumption might be violated in the model.</p>
<p>Individual tests: These are separate tests for each covariate in the model. If the p-value for a covariate is not significant (p &gt; 0.05), it indicates that the assumption hold for that covariate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcoxzph</span>(cox_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If the lines in the diagnostic plot are roughly horizontal, it suggests that the proportional hazards assumption holds.</p></li>
</ol>
<p>Screening for influential factors and building the best model are key steps in Cox regression analysis. Methods such as univariate analysis, stepwise regression, and LASSO regression can effectively select variables. Evaluation metrics like AIC and C-index help assess model performance, ultimately leading to a model that is both interpretable and accurate in predicting survival outcomes.</p>
<p><strong>Output interpretation</strong></p>
<p>When fitting a Cox model using the <code>coxph()</code> function, the output provides estimated coefficients, hazard ratios, and results for hypothesis tests.</p>
<ol type="1">
<li><p><strong>Coefficients (coef)</strong></p>
<p>These represent the estimated coefficients for the covariates in the model. A positive coefficient indicates that the covariate is associated with an increased hazard (risk of the event), and a negative coefficient indicates a decreased hazard (protective factor).</p></li>
<li><p><strong>Hazard ratios (exp(coef))</strong></p>
<p>The hazard ratio is the exponentiated coefficient (<span class="math inline">e^{\text{coef}}</span>) and indicates the multiplicative effect of the covariate on the hazard. A hazard ratio of 1 indicates no effect, greater than 1 indicates an increased hazard, and less than 1 indicates a decreased hazard.</p></li>
<li><p><strong>p-value</strong></p>
<p>The p-value tests the null hypothesis that the coefficient is zero (no effect). A small p-value (usually &lt; 0.05) indicates that the covariate has a statistically significant effect on the hazard.</p></li>
<li><p><strong>95% CI for exp(coef)</strong></p>
<p>These provide a range of plausible values for the hazard ratio. If the confidence interval does not include 1, the effect of the covariate is considered statistically significant. A 95% CI that lies entirely above 1 suggests a positive association (increased hazard), while a CI below 1 suggests a negative association (decreased hazard).</p></li>
<li><p><strong>Likelihood ratio test, Wald test, and Score (logrank) test</strong></p>
<p>These tests assess the overall significance of the Cox model. Likelihood ratio test compares the likelihood of the model with covariates to the likelihood without covariates. Wald test assesses whether the coefficients are significantly different from zero. Score test (Log-rank test) is similar to the likelihood ratio test, but uses a different method for assessment.</p></li>
<li><p><strong>Concordance (c-index)</strong></p>
<p>The concordance index (or c-index) measures the predictive accuracy of the model, indicating how well the model predicts the ordering of survival times. A c-index of 0.5 indicates random predictions, while a value closer to 1 indicates better predictive power.</p></li>
</ol>
<div class="example">
<strong>Example 5</strong> 
<p>To investigate the prognosis of a certain malignant tumor, a researcher collected survival times, survival outcomes, and influencing factors for 63 patients. The influencing factors include patient age, gender, histological type, treatment method, lymph node metastasis, and tumor infiltration depth. The survival time, denoted as t , is measured in months. The variable coding is shown in <a href="#tbl-cox-tumor" class="quarto-xref">Table&nbsp;<span>21.2</span></a> . Perform an analysis on the data using Cox regression model.</p>
</div>
<div>
<p><a href="datasets/ex21-04.csv" download="ex21-04.csv" class="btn btn-success"> <i class="bi bi-database-fill-down"></i> Download data </a></p>
</div>
<div class="cell">
<div id="tbl-cox-tumor" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cox-tumor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.2: Influencing factors and assignment of a malignant tumor
</figcaption>
<div aria-describedby="tbl-cox-tumor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 9%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Factor</th>
<th style="text-align: center;">Variable</th>
<th style="text-align: left;">Assignment specification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: center;">X1</td>
<td style="text-align: left;">(Year)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender</td>
<td style="text-align: center;">X2</td>
<td style="text-align: left;">Female＝0，Male＝1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Histology type</td>
<td style="text-align: center;">X3</td>
<td style="text-align: left;">Poorly differentiated＝0，Well differentiated＝1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Therapeutic method</td>
<td style="text-align: center;">X4</td>
<td style="text-align: left;">Traditional＝0，New＝1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lymphatic metastasis</td>
<td style="text-align: center;">X5</td>
<td style="text-align: left;">No＝0，Yes＝1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Degree of tumor invasion</td>
<td style="text-align: center;">X6</td>
<td style="text-align: left;">Not penetrated the serosal layer＝0，Penetrated the serosal layer＝1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Survival time</td>
<td style="text-align: center;">t</td>
<td style="text-align: left;">(Month)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Survival status</td>
<td style="text-align: center;">Y</td>
<td style="text-align: left;">Censored＝0，Dead＝1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>tb <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datasets/ex21-04.csv"</span>, <span class="at">show_col_types =</span> F) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can use the <code>coxph()</code> function from the <code>survival</code> package to fit a Cox model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>cox_model <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(t, y) <span class="sc">~</span> ., <span class="at">data =</span> tb)   </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggforest</span>(cox_model, <span class="at">data =</span> tb, <span class="at">main =</span> <span class="st">""</span>, <span class="at">fontsize =</span> <span class="fl">0.9</span>, <span class="at">noDigits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="survival-analysis_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>The function <code>ggforest()</code> in the survminer package is used to generate a forest plot for a Cox proportional hazards model. The forest plot is a graphical representation of the hazard ratios (HR) for each covariate included in the Cox model, along with their confidence intervals.</p>
<p>For each covariate, the plot shows how much it increases or decreases the hazard. THe HR &gt; 1 suggest an increased hazard, while HR &lt; 1 suggest a reduced hazard. If the confidence interval crosses 1, it indicates that the variable might not be statistically significant at the chosen significance level.</p>
<p>A forest plot makes it easier to visually compare the relative effect sizes of different variables in the Cox model. It’s commonly used in research papers to succinctly summarize Cox regression results. It helps researchers understand which factors have a large or small impact on survival in their study.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>optimal_model <span class="ot">&lt;-</span> <span class="fu">step</span>(cox_model, <span class="at">direction =</span> <span class="st">"both"</span>, <span class="at">trace =</span> <span class="dv">0</span>) </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(optimal_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Call:
#&gt; coxph(formula = Surv(t, y) ~ X4 + X5, data = tb)
#&gt; 
#&gt;   n= 63, number of events= 26 
#&gt; 
#&gt;       coef exp(coef) se(coef)      z Pr(&gt;|z|)   
#&gt; X4 -1.7830    0.1681   0.5479 -3.254  0.00114 **
#&gt; X5  0.9395    2.5587   0.4446  2.113  0.03460 * 
#&gt; ---
#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#&gt; 
#&gt;    exp(coef) exp(-coef) lower .95 upper .95
#&gt; X4    0.1681     5.9477   0.05745    0.4921
#&gt; X5    2.5587     0.3908   1.07044    6.1163
#&gt; 
#&gt; Concordance= 0.752  (se = 0.043 )
#&gt; Likelihood ratio test= 19.65  on 2 df,   p=5e-05
#&gt; Wald test            = 14.87  on 2 df,   p=6e-04
#&gt; Score (logrank) test = 18.02  on 2 df,   p=1e-04</code></pre>
</div>
</div>
<p>The Cox model output provides insights into the relationship between the covariates and the survival time (or event occurrence).</p>
<blockquote class="blockquote">
<ol type="1">
<li><p><strong>Model fit summary</strong></p>
<ul>
<li>n = 63: There were 63 individuals in the dataset.</li>
<li>number of events = 26: Out of these 63 individuals, 26 experienced the event of interest (e.g., death, relapse).</li>
</ul></li>
<li><p><strong>Coefficients and hazard ratios</strong></p>
<ul>
<li><span class="math inline">X_4</span>: Coefficient is -1.7830: This indicates that <span class="math inline">X_4</span> is negatively associated with the hazard of the event. A negative coefficient means that an increase in <span class="math inline">X_4</span> decreases the hazard (or risk). The HR = 0.1681, since the hazard ratio is less than 1, it suggests that <span class="math inline">X_4</span> is protective (reduces the risk). Specifically, a one-unit increase in <span class="math inline">X_4</span> decreases the hazard by 83.19% (calculated as 1 - 0.1681 = 0.8319). The p-value is 0.00114, this is highly significant, meaning there is strong evidence that <span class="math inline">X_4</span> has an effect on survival.</li>
<li><span class="math inline">X_5</span>: Coefficient is 0.9395: This indicates that <span class="math inline">X_5</span> is positively associated with the hazard of the event. A positive coefficient means that an increase in <span class="math inline">X_5</span> increases the hazard (or risk). The HR = 2.5587, a hazard ratio greater than 1 means that <span class="math inline">X_5</span> increases the hazard. Specifically, a one-unit increase in <span class="math inline">X_5</span> multiplies the hazard by approximately 2.56, meaning a 156% increase in the risk of the event. The p-value is 0.03460, this is also statistically significant, indicating that <span class="math inline">X_5</span> has a meaningful effect on survival.</li>
</ul></li>
<li><p><strong>CI for HR</strong></p>
<ul>
<li><span class="math inline">X_4</span>: The 95% CI for the hazard ratio of <span class="math inline">X_4</span> is (0.05745, 0.4921). This means we are 95% confident that the true hazard ratio lies between these values. Since this interval does not include 1, <span class="math inline">X_4</span> has a statistically significant protective effect.</li>
<li><span class="math inline">X_5</span>: The 95% CI for the hazard ratio of <span class="math inline">X_5</span> is (1.07044, 6.1163). Since this interval is entirely above 1, it confirms that <span class="math inline">X_5</span> significantly increases the hazard.</li>
</ul></li>
<li><p>Model Performance Metrics</p>
<ul>
<li><p>Concordance = 0.752: This measures the model’s predictive accuracy. A concordance of 0.752 means that in 75.2% of the pairs of subjects, the model correctly predicts which one experienced the event first.</p></li>
<li><p>Likelihood ratio test: A test of the overall significance of the model. The p-value (<span class="math inline">p</span> = 5e-05) is highly significant, indicating that the model as a whole explains a significant portion of the variation in the hazard.</p></li>
<li><p>Wald test: This tests the significance of the coefficients collectively. The p-value (<span class="math inline">p</span> = 6e-04) is also significant, suggesting that the covariates in the model are jointly significant.</p></li>
<li><p>Score (logrank) test: Another test of the model’s significance, with a highly significant p-value (<span class="math inline">p</span> = 1e-04).</p></li>
</ul></li>
</ol>
</blockquote>
<p>It’s important to check if the proportional hazards assumption holds for your data. You can use the <code>cox.zph()</code> function to test this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check proportional hazards assumption</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>cox_test <span class="ot">&lt;-</span> <span class="fu">cox.zph</span>(optimal_model, <span class="at">transform =</span> <span class="st">"km"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>cox_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;        chisq df     p
#&gt; X4     2.835  1 0.092
#&gt; X5     0.149  1 0.700
#&gt; GLOBAL 2.990  2 0.224</code></pre>
</div>
</div>
<p>This is the output from the <code>cox.zph()</code> test, which checks the proportional hazards assumption for each covariate in a Cox model, as well as a global test that examines the assumption across all covariates in the model.</p>
<blockquote class="blockquote">
<ul>
<li><span class="math inline">X_4</span>: The p-value is 0.092, which is greater than the significance level of 0.05. This indicates that there is no strong evidence to reject the null hypothesis that the proportional hazards assumption holds for <span class="math inline">X_4</span>. However, the p-value is somewhat close to 0.05, suggesting that the assumption might be slightly violated for <span class="math inline">X_4</span>. You should inspect the plot for <span class="math inline">X_4</span> to see if there are any obvious trends.</li>
<li><span class="math inline">X_5</span>: The p-value is 0.700, which is well above 0.05. This suggests that there is no evidence of violation of the proportional hazards assumption for <span class="math inline">X_5</span>. The assumption holds well for this covariate.</li>
<li>Global: The global p-value is 0.224, which is also greater than 0.05. This means that, overall, there is no significant evidence to suggest that the proportional hazards assumption is violated for the model as a whole.</li>
</ul>
</blockquote>
<p>The plots display the scaled Schoenfeld residuals for the covariates <span class="math inline">X_4</span> and <span class="math inline">X_5</span>. These residuals help in assessing the proportional hazards assumption in the Cox proportional hazards model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcoxzph</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  cox_test, <span class="at">point.col =</span> <span class="st">"blue"</span>, <span class="at">point.size =</span> <span class="fl">1.3</span>, <span class="at">point.shape =</span> <span class="dv">1</span>, </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.title =</span> <span class="dv">9</span>, <span class="at">font.x =</span> <span class="dv">9</span>, <span class="at">font.y =</span> <span class="dv">9</span>, <span class="at">font.tickslab =</span> <span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="survival-analysis_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The lines in the diagnostic plot are roughly horizontal, it suggests that the proportional hazards assumption holds.</p>
</blockquote>
<p>If the proportional hazards assumption does not hold, you could consider:</p>
<ul>
<li>Stratified cox models: If the non-proportionality is due to specific covariates, you can stratify by these variables.</li>
<li>Time-dependent covariates: If the hazard ratio changes over time, including time-dependent covariates in the model might address this issue.</li>
</ul>
<p>You can also visualize the survival curves for each group using the <code>ggsurvplot()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">survfit</span>(optimal_model),</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tb,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Time(month)"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Survival Probability"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pval.size =</span> <span class="fl">3.8</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">censor.shape =</span> <span class="dv">1</span>,</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">censor.size =</span> <span class="dv">2</span>, </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend =</span> <span class="st">"none"</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.int =</span> F,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> <span class="fl">0.5</span>,</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.x =</span> <span class="dv">9</span>,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.y =</span> <span class="dv">9</span>,</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.tickslab =</span> <span class="dv">9</span>,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">font.legend =</span> <span class="dv">9</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="survival-analysis_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>This will generate Kaplan-Meier survival curves based on the fitted Cox model, allowing you to visually compare the survival distributions between groups.</p>
<p>The Cox model is a flexible and powerful tool for assessing the impact of various covariates on survival times without making assumptions about the underlying survival distribution. It is especially useful for analyzing clinical and observational data where the event of interest is subject to right-censoring.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/qbgaoo\.github\.io\/r4ms");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./generalized-linear-model.html" class="pagination-link" aria-label="Generalized linear model">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Generalized linear model</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./cluster-analysis.html" class="pagination-link" aria-label="Cluster analysis">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Cluster analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://qbgaoo.github.io/r4ms/edit/main/survival-analysis.qmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://qbgaoo.github.io/r4ms/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>